### ISSUE TITLE
How to add uid to all files

### ISSUE THREAD

**Issue by GCRVL** [jmbannon/ytdl-sub#1000]
Sorry, really can't figure out how to do this in the documentation.

Jellyfin Youtube Metadata plugin says:

> File Naming Requirements
> All media needs to have the ID embeded in the file name within square brackets. The following are valid examples of a channel and video.
> 
> 3Blue1Brown - NA - 3Blue1Brown_-_Videos [UCYO_jab_esuFRV4b17AJtAw].info.json
> 3Blue1Brown - 20211023 - A_few_of_the_best_math_explainers_from_this_summer [F3Qixy-r_rQ].mkv

My subscriptions is basic:

```# Overrides to the prebuilt presets
__preset__:
  overrides:
    # For 'Only Recent' preset, only keep vids within this range and limit
    only_recent_date_range: "3year"
    only_recent_max_files: 4
    tv_show_directory: "/youtube"

# Choose the player you intend to use by setting the top-level key to be either:
#   - Plex TV Show by Date:
#   - Jellyfin TV Show by Date:
#   - Kodi TV Show by Date:
Jellyfin TV Show by Date | best_video_quality | no_shorts | chunk_initial_download:
  # Set "News" for genre, use `Only Recent` preset to only store videos uploaded recently
  = Channels:
    "Jacob Geller": "https://www.youtube.com/@JacobGeller"
    "Historia Civilis": "https://www.youtube.com/@HistoriaCivilis"
```

How do I change the filename for all generated files in order to achieve this?

I don't need to Season folders, are these disableable?

**Comment by jmbannon** [comment]
@GCRVL  you do not need to use the Youtube metadata plugin, simply use local file metadata and it should work out of the box

**Comment by jmbannon** [comment]
Closing but still happy to help if needed
