### ISSUE TITLE
Removing "Only Recent" from a channel does not trigger a full channel download

### ISSUE THREAD

**Issue by GCRVL** [jmbannon/ytdl-sub#1002]
I device my channels in two presets, one with "Only Recent" and one without, for those few channels worthy of deserving to be fully archived.

I believe I encountered a bug:

1.  Put a channel into the "Only Recent" preset.
2.  Run ` ytdl-sub sub subscriptions.yaml`
3. Move channel into a preset without "Only Recent"
4.  Run ` ytdl-sub sub subscriptions.yaml`
5.  Full channel is not downloaded

Upping the `only_recent_max_files: 6` value after a full sub download also does not retrigger download.

![image](https://github.com/jmbannon/ytdl-sub/assets/4420162/5864d76e-5dea-4645-8550-6759ad51f4c0)

In the screenshot you can observe both issues:

1. The channel "LEMMiNO" used to be in "Only Recent" now not anymore. The whole channel is not being downloaded.
2. only_recent_max_files used to be 4, is now 6, videos are not being downloaded.

**Comment by jmbannon** [comment]
See https://ytdl-sub.readthedocs.io/en/latest/faq/index.html#date-range-is-not-downloading-older-videos-after-i-changed-the-range
