### ISSUE TITLE
Feature Request: Parallel Downloads

### ISSUE THREAD

**Issue by Noodlez1232** [jmbannon/ytdl-sub#1003]
Some internet connections will throttle single downloads, but will allow multiple downloads at a time (at the throttled rate). In these situations, or when downloading from multiple sources (e.g. some from YouTube, some from PeerTube, some from Bandcamp), it might be beneficial to allow downloading multiple streams at a time, in parallel.

**Comment by jmbannon** [comment]
Going to close since parallelism most likely won't be added to the core implementation, but still happy to walk you through on how to parallelize downloads via bash
