### ISSUE TITLE
Ignore certain videos?

### ISSUE THREAD

**Issue by joeybab3** [jmbannon/ytdl-sub#1004]
Tried to peruse the docs and faq so forgive me if I have missed where this is explained, but is there a way to ignore certain videos or blacklist/delete them without redownloading?

Can I just delete the video files that are downloaded but leave the metadata files and it won't try and redownload or how would I go about this? There are some like 36 hour live streams I wanted to discard

**Comment by jmbannon** [comment]
Deleting them will not redownload them (assumining you're using TV show presets). ytdl-sub only looks at the download archive to determine if a vid is downloaded, and will continue to think it is even if the file is deleted.

For filtering live vids, see the example here:
https://ytdl-sub.readthedocs.io/en/latest/config_reference/plugins.html#match-filters

**Comment by jmbannon** [comment]
Closing but still happy to help if needed
