### ISSUE TITLE
Redownloading already downloaded videos

### ISSUE THREAD

**Issue by antistereov** [jmbannon/ytdl-sub#1024]
Hey there,
sorry if this issue due to me being unable to read docs!

**What happened?**
I created my `subscriptions.yaml` and `config.yaml` and downloaded all the videos using:

```bash
ytdl-sub -c ./config.yaml sub ./subscriptions.yaml
```

This worked out perfectly fine. 684 videos were downloaded, all the `.ytdl-sub-<name>-archive.json` files were created and the files are perfect.

Now, I wanted to download the new videos but everytime when I run the same command, it started to download everything again. Here's the output before I canceled:

[logs.txt](https://github.com/user-attachments/files/16319835/logs.txt)

I checked the paths, rerun with the `Jellyfin TV Show by Date` preset in case there is something wrong with my config, added the `download_archive` to my config, changed `break_on_existing` to `true` but still it downloads all the videos again and again. I even checked on Windows.

Here's my config: [config.txt](https://github.com/user-attachments/files/16319801/config.txt) and my subscriptions: [subscriptions.txt](https://github.com/user-attachments/files/16319807/subscriptions.txt). (I had to change it to .txt so I can upload it to GitHub. Appearantly .yaml aren't supported in GitHub issues.)

Thank you very much for creating this tool!

**Comment by jmbannon** [comment]
Remove ytdl_options.download_archive -- that will mess up ytdl-sub's custom download archive logic.

Rerun with --log-level debug and upload the contents to pastebin

**Comment by antistereov** [comment]
I tested again today and can't replicate the issue. Very weird. I don't know what happened yesterday. Thank you very much for your help! Your tool is amazing!
