### ISSUE TITLE
Help with exclude

### ISSUE THREAD

**Issue by mtompkins** [jmbannon/ytdl-sub#1025]
Thanks in advance for a little assistance

I'm trying to prevent the download of files from a channel based on filters. Largely this is working as intended.
My problem is when a title has a subset that I need to filter.

Example - given two titles as follows:
- "AAA"
- "AAA and 123"

How can I filter "AAA" without filtering "AAA and 123"?

Using the `%contains` operative understandable fails.
You don't seem to have an explicit match operative ...

```
filtered_videos:
  filter_exclude:
      - >-
        { %contains(title, 'AAA' ) }
```

**Comment by jmbannon** [comment]
You'll need to use the `and` function, something like
```
filtered_videos:
  filter_exclude:
      - >-
        {
          %and(
            %contains(title, 'AAA' ),
            %not( %contains(title, '123') )
          )
        }
```

**Comment by jmbannon** [comment]
Alternatively you can use a regex match function:
https://ytdl-sub.readthedocs.io/en/latest/config_reference/scripting/scripting_functions.html#regex-match

**Comment by mtompkins** [comment]
Thank you so much!
