### ISSUE TITLE
List support for `ytdl-sub dl`

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#103]
It assumes all fields are `key.sub_key.value`. Should support lists like `--my_preset.regex.from.title.match._1 'value'`

**Comment by MariaMozgunova** [comment]
Hello,
I found this repo in the [Good First Issues](https://goodfirstissues.com/) aggregator.
Can I take this issue?

**Comment by jmbannon** [comment]
@MariaMozgunova go for it! Here are some some code pointers:

Class that handles `ytdl-sub dl` arguments: https://github.com/jmbannon/ytdl-sub/blob/master/src/ytdl_sub/cli/download_args_parser.py#L12
tests: https://github.com/jmbannon/ytdl-sub/blob/master/tests/unit/cli/test_download_args_parser.py

**Comment by MariaMozgunova** [comment]
@jmbannon Could you please verify whether I am moving in the right direction?
This issue targets implementing the following: Match presets against the regex, and once there is a match, set the preset value to `'value'`. Is that right?

**Comment by jmbannon** [comment]
@MariaMozgunova sorry I should have been more specific in description.

For context, `ytdl-sub dl --regex.from.title.match "a string"` will create a dict that looks like:
```
{
  "regex": {
    "from": {
      "title": {
        "match": "a string"
      }
    }
  }
}
```
We want to add list support to this CLI syntax. So `ytdl-sub dl --some.nested_list._1 "a string"` should translate to
```
{
  "some": {
    "nested_list": [
      "a string"
    ]
  }
}
```

**Comment by jmbannon** [comment]
The regex example in the description is an actual config parameter that uses a list - should probably be used to test.

**Comment by jmbannon** [comment]
Another thing that should be tested is to ensure the list elements are sequential from 1-n, i.e.
```
existing_list: ['one_element']
# can specify existing_list._1 (replaces the first element)
# can specify existing_list._2 (appends an element)
# CANNOT specify existing_list._3 (unless ._2 is also specified)
```

**Comment by MariaMozgunova** [comment]
Thank you for the clarifications! 
Which config parameters exactly can use a list, or any of them can? 

Should the parameters be parsed sequentially?
So, would the following example:
```
ytdl-sub dl --existing_list._3 'v3' --existing_list._2 'v2' --existing_list._1 'v1'
``` 
create only `existing_list: ['v1']`?

**Comment by jmbannon** [comment]
Order shouldn't matter so long as the end-result is sequential. The above should produce `['v1', 'v2', 'v3']`

Only the regex one I mentioned above uses lists but a future parameter could also be a list. For the sake of this task + testing it, lets not worry about the existing ones. The test can make one up

**Comment by MariaMozgunova** [comment]
Can the following happen: `--my_preset.regex.from.title.match._1 'v1' --my_preset.regex.from.title.match 'v2'`?
So, can some config parameter be both list and non-list? What should happen in the case above?

**Comment by jmbannon** [comment]
Lets throw an exception in that case.

Lets make a new one here: https://github.com/jmbannon/ytdl-sub/blob/master/src/ytdl_sub/utils/exceptions.py
`InvalidDlArguments(ValidationException)`

**Comment by MariaMozgunova** [comment]
Why it is necessary to use this syntax: `ytdl-sub dl --some.list._1 'v1' --some.list._2 'v2'`?

Why not do the following: `ytdl-sub dl --some.list ['v1', 'v2']`?

**Comment by jmbannon** [comment]
> 

Good question. Someone could have the first element already defined and only want to add a second element. I think it makes sense to support both. The ['v1', 'v2'] feature can be done in a follow-up PR

**Comment by MariaMozgunova** [comment]
In the case you mentioned, where can be the first element already defined? How to know that the first element is already defined?

**Comment by MariaMozgunova** [comment]
Is it still relevant to implement the following behavior: `ytdl-sub dl --some.list ['v1', 'v2']`?

**Comment by jmbannon** [comment]
@MariaMozgunova Missed this, would be nice but it's not high-priority
