### ISSUE TITLE
Repeatly getting this error

### ISSUE THREAD

**Issue by fisherd80** [jmbannon/ytdl-sub#1043]
Hello,

I have been using ytdl-sub for number of weeks without issue.  But over the last few days I have been getting the following error.

> 
> Traceback (most recent call last):
> File "/usr/lib/python3.12/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 375, in exception_handling
> yield
> File "/usr/lib/python3.12/site-packages/ytdl_sub/cli/entrypoint.py", line 126, in _download_subscriptions_from_yaml_files
> subscription.download(dry_run=dry_run)
> File "/usr/lib/python3.12/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 362, in download
> return self._process_subscription(
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/lib/python3.12/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 306, in _process_subscription
> entry = downloader.download(entry)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/lib/python3.12/site-packages/ytdl_sub/downloaders/url/downloader.py", line 529, in download
> download_entry = self._extract_entry_info_with_retry(entry=entry)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/lib/python3.12/site-packages/ytdl_sub/downloaders/url/downloader.py", line 352, in _extract_entry_info_with_retry
> download_entry_dict = YTDLP.extract_info_with_retry(
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/lib/python3.12/site-packages/ytdl_sub/downloaders/ytdlp.py", line 137, in extract_info_with_retry
> raise FileNotDownloadedException(
> ytdl_sub.utils.exceptions.FileNotDownloadedException: yt-dlp failed to download an entry with these arguments: {'ytdl_options': {'ignoreerrors': True, 'outtmpl': '/tmp/Biffa Plays Indie Games/%(id)S.%(ext)s', 'writethumbnail': True, 'ffmpeg_location': '/usr/bin/ffmpeg', 'download_archive': '/tmp/Biffa Plays Indie Games/.ytdl-sub-Biffa Plays Indie Games-download-archive.json-ytdl-archive', 'merge_output_format': 'mp4', 'postprocessors': [{'key': 'FFmpegVideoRemuxer', 'when': 'post_process', 'preferedformat': 'mp4'}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}], 'format': "(bv*[ext=mp4][vcodec~='^((he|a)vc|h26[45])']+ba[ext=m4a]) / (bv[ext=mp4]*+ba[ext=m4a]/b)", 'break_on_existing': False, 'cookiefile': '/config/cookie.txt'}, 'kwargs': {'url': 'https://www.youtube.com/watch?v=HUZf-aJvlI0'}}

I can't make heads or tails of what seems to wrong as this error wont allow for any more files to be download for any of the subscription . Each subscription get the same error (except the video file name are different for the channels).

Can anyone advise.

**Comment by jmbannon** [comment]
Should be fixed by the above PR, please reopen if that is not the case.
