### ISSUE TITLE
How to use max_1080p

### ISSUE THREAD

**Issue by ItsNoted** [jmbannon/ytdl-sub#1063]
I've been perusing the docs for a couple days trying to wrap my head around this amazing app. I have a working subscriptions.yaml file below.

```

__preset__:
  overrides:
    tv_show_directory: "/mnt/media/Youtube/Jeremy"
    only_recent_date_range: "2months"
    only_recent_max_files: 5

Jellyfin TV Show by Date:

  = Youtube | Only Recent:
    "Matt Carriker": "https://www.youtube.com/@OffTheRanch"
```

How can I implement the max_1080p so it downloads in 1080p at a smaller MP4 file size rather than a full size webm file? I've tried adding it to the overrides section but to no avail, it did not work.

**Comment by jmbannon** [comment]
presets can be added via `|` on subscription keys, so either `Jellyfin TV Show by Date | max_1080p:` or `= Youtube | Only Recent | max_1080p` will work

**Comment by jmbannon** [comment]
Love your site btw @ItsNoted ! Let me know if you ever decide to do a write up on ytdl-sub, would be happy to help in any way

**Comment by ItsNoted** [comment]
That's the plan once I can figure out more of the advanced features. I'm really enjoying this so far! Thanks for the quick response on this. I like the challenging aspect of it and it's been a while since I've had to really dig through docs to get something working the way I need it.

**Comment by ItsNoted** [comment]
Does it make any difference if we use the cookie file? Will it speed up downloads or make the process any smoother?

**Comment by jmbannon** [comment]
@ItsNoted  Cookie file is really only needed to download mature content. Though you are at risk of getting your acct IP-banned, so be cautious and use throttle protection if you do so (https://ytdl-sub.readthedocs.io/en/latest/config_reference/plugins.html#throttle-protection)

For filtering, yes absolutely. We recently improved this (see https://github.com/jmbannon/ytdl-sub/releases/tag/2024.09.20), you can do something like this:

`config.yaml`
```
presets:
  title_exclude_filters:
    filter_exclude:
      - "{%contains_any( %lower(title), title_exclude_strings )}"
  overrides:
    title_exclude_strings:
      - "DUMMY DEFAULT STRING SHOULD NEVER EXCLUDE"  # to be overwritten if needed
```

Then in your subscriptions:
```
Jellyfin TV Show by Date | title_exclude_filters:
  "~Joe Rogan":
    url: "https://..."
    title_exclude_strings:
      - "mma"
      - "clip"
   
  "Different Sub No Filtering Needed":  "https://..."
  ```

**Comment by ItsNoted** [comment]
Awesome thank you!

**Comment by ItsNoted** [comment]
I'm writing and article and had a couple questions for you. What's the best way to communicate with you in this regard?

**Comment by jmbannon** [comment]
You can find me in the ytdl-sub discord, feel free to DM: https://discord.gg/v8j9RAHb4k
