### ISSUE TITLE
Scripting string splits with newline separator

### ISSUE THREAD

**Issue by Leaguesman** [jmbannon/ytdl-sub#1094]
Hi,

Really enjoying using this so far, and am now digging more into some advanced scripting to get some cleaner metadata out of the YouTube exports. I have a sub for which I only want to save the first line of the description. 

This seems like it should be possible with the scripting functions, but I'm probably making a rookie error. I've got this as the overrides of my custom preset:

>     overrides:
>       description_to_array: >-
>         {
>           %split(description, "\n")
>         }
>       first_line_of_description: >-
>         {
>           %array_at(description_to_array, 0)
>         }
>       episode_plot: "{first_line_of_description}"

Which just returns the entire description, seemingly not having split it at all. Escaping the newline character doesn't appear to work either, and as far as I'm aware looking at the underlying code of ytdl-sub, you're wrapping the basic python string split function to do this, which should accept something in the form of str.split('\n').

Thanks for any advice you can give.

**Comment by jmbannon** [comment]
My guess is it's not translating to newline from yaml. I will look into this soon

**Comment by jmbannon** [comment]
@Leaguesman should now be supported in the latest version

**Comment by jmbannon** [comment]
Slightly changed to preserve original parsing logic. Use `%split(description, %unescape("\n"))` to translate to an actual newline
