### ISSUE TITLE
[feature] Ability to add debrid links instead of dl

### ISSUE THREAD

**Issue by andyhawks** [jmbannon/ytdl-sub#1097]
Would be great to have the ability to use ytdl-sub to add video links to Real Debrid or All Debrid instead of dling, and still get the media with metadata into chosen media server (e.g. with a zurg mount or something).

**Comment by jmbannon** [comment]
The closest thing that I plan to build out someday that could maybe work for this this use-case is local file support - basically using any metadata you have from a set of given files to run through ytld-sub. That is tracked here: https://github.com/jmbannon/ytdl-sub/issues/155
