### ISSUE TITLE
FunctionRuntimeException: Runtime error occurred when executing the function %from_json: Invalid control character

### ISSUE THREAD

**Issue by jacroe** [jmbannon/ytdl-sub#1107]
Only when downloading certain channels and playlists, I get a `ytdl_sub.script.utils.exceptions.FunctionRuntimeException: Runtime error occurred when executing the function %from_json: Invalid control character at: line 1 column 385820 (char 385819)` with the column and char numbers being different.

Here's the console log with verbose logging: [console.log](https://github.com/user-attachments/files/17535263/console.log)

I'm running the [`latest` docker image](https://github.com/jmbannon/ytdl-sub/pkgs/container/ytdl-sub/295858606?tag=latest)

**Comment by jmbannon** [comment]
Thanks for posting this issue, verified lofi girl downloads correctly locally with this fix

**Comment by jacroe** [comment]
Can confirm! Thank you!
