### ISSUE TITLE
Subtitles downloading error

### ISSUE THREAD

**Issue by willowless** [jmbannon/ytdl-sub#1110]
Primitive Technology is an amazing channel but you need subtitles to know what's going on. Trying to pull it with subtitles is giving me an error:

[ytdl-sub:downloader] Downloading entry 9/27: Primitive Technology: Making Charcoal (3 Different Methods)
[ytdl-sub] The following error occurred for the subscription Primitive Technology:
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 388, in exception_handling
    yield
  File "/usr/lib/python3.12/site-packages/ytdl_sub/cli/entrypoint.py", line 126, in _download_subscriptions_from_yaml_files
    subscription.download(dry_run=dry_run)
  File "/usr/lib/python3.12/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 375, in download
    return self._process_subscription(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 315, in _process_subscription
    entry = downloader.download(entry)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ytdl_sub/downloaders/url/downloader.py", line 529, in download
    download_entry = self._extract_entry_info_with_retry(entry=entry)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ytdl_sub/downloaders/url/downloader.py", line 352, in _extract_entry_info_with_retry
    download_entry_dict = YTDLP.extract_info_with_retry(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ytdl_sub/downloaders/ytdlp.py", line 137, in extract_info_with_retry
    raise FileNotDownloadedException(
ytdl_sub.utils.exceptions.FileNotDownloadedException: yt-dlp failed to download an entry with these arguments: {'ytdl_options': {'ignoreerrors': True, 'outtmpl': '.ytdl-sub-working-directory/Primitive Technology/%(id)S.%(ext)s', 'writethumbnail': True, 'ffmpeg_location': '/usr/bin/ffmpeg', 'download_archive': '.ytdl-sub-working-directory/Primitive Technology/.ytdl-sub-Primitive Technology-download-archive.json-ytdl-archive', 'merge_output_format': 'mp4', 'postprocessors': [{'key': 'FFmpegVideoRemuxer', 'when': 'post_process', 'preferedformat': 'mp4'}, {'key': 'FFmpegSubtitlesConvertor', 'format': 'srt'}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}], 'writesubtitles': True, 'writeautomaticsub': False, 'subtitleslangs': ['en'], 'format': "(bv*[ext=mp4][vcodec~='^((he|a)vc|h26[45])']+ba[ext=m4a]) / (bv[ext=mp4]*+ba[ext=m4a]/b)", 'break_on_existing': True, 'cookiefile': '/config/cookie.txt'}, 'kwargs': {'url': 'https://www.youtube.com/watch?v=JsObuHO1tMA'}}

[ytdl-sub.errorsd1q30vib.zip](https://github.com/user-attachments/files/17548707/ytdl-sub.errorsd1q30vib.zip)

config.yaml
presets:
  Subtitles:
    subtitles:
      subtitles_name: "{episode_file_path}.{lang}.{subtitles_ext}"
      subtitles_type: "srt"
      embed_subtitles: False
      allow_auto_generated_subtitles: False

subscriptions.yaml
Plex TV Show by Date:
  # Sets genre tag to "Documentaries"
  = Shows | Subtitles:
    "Primitive Technology": "https://www.youtube.com/@primitivetechnology9550"

**Comment by jmbannon** [comment]
Looks like you didn't include the error log @willowless , can you instead rerun with --log-level debug and paste the output of that
