### ISSUE TITLE
[question] download subtitles for existing videos

### ISSUE THREAD

**Issue by diblaze** [jmbannon/ytdl-sub#1139]
Is there any way to download subtitles for already downloaded videos?

I need subtitles as I can not listen to all videos because of my surroundings. Subtitles help where applicable. 

Currently I delete videos and force redownload them.

**Comment by jmbannon** [comment]
Unfortunately not, as of now you must delete + redownload

**Comment by nullicist-aakash** [comment]
Hi, is this still not supported?

**Comment by jmbannon** [comment]
Only downloading subtitles is still not supported, though I think I will make this a feature request given the frequency of it getting asked.
