### ISSUE TITLE
Add list support for music_tags plugin

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#120]
id3v2.4 tags allow lists. We should be able to write those.

The music_tags plugin uses beets' mediafile package: https://github.com/beetbox/mediafile/blob/master/mediafile.py
You can see some fields are ListMediaField. Those are the ones that should be able to support list values in ytdl-sub

Task: Support id3v2.4 lists by specifying a list in music_tags.tags.<some_field>
https://github.com/jmbannon/ytdl-sub/blob/master/src/ytdl_sub/plugins/music_tags.py#L76

subtask: These fields should support both strings and list of strings.
https://github.com/jmbannon/ytdl-sub/blob/master/src/ytdl_sub/plugins/music_tags.py#L42

subtask: We should verify the specified field supports lists prior to any downloading. This would need to happen in the

**Comment by MariaMozgunova** [comment]
Can I take this issue?

**Comment by jmbannon** [comment]
> Can I take this issue?

Lets get your other PR in first :-)

**Comment by jmbannon** [comment]
Do you still want to take this @MariaMozgunova ?

**Comment by MariaMozgunova** [comment]
@jmbannon Could you answer a few questions?

There is an example [https://github.com/jmbannon/ytdl-sub/blob/master/src/ytdl_sub/plugins/music_tags.py#L30-L33](https://github.com/jmbannon/ytdl-sub/blob/master/src/ytdl_sub/plugins/music_tags.py#L30-L33) for non-list tags. What will it look like for the list tags?

For the first subtask, the new `FormatterValidator` needs to be declared?

The second subtask seems to be incomplete.

**Comment by jmbannon** [comment]
> @jmbannon Could you answer a few questions?
> 
> There is an example https://github.com/jmbannon/ytdl-sub/blob/master/src/ytdl_sub/plugins/music_tags.py#L30-L33 for non-list tags. What will it look like for the list tags?

It should be a YAML list of strings (in the backend, list of StringFormatValidators so variables can be used)

> For the first subtask, the new `FormatterValidator` needs to be declared?

I think two validators should be made: a StringFormatListValidator, and a MusicTagValidator that inherits from it.

> The second subtask seems to be incomplete.

My bad. Was going to say the MusicTagValidator should ensure the tag supports lists (i.e. artists does, not artist). See the MediaFile dep source code to see which ones are lists or not. This validation should be in the MusicTagValidator init.

Hopefully that makes sense 😅
