### ISSUE TITLE
Prevent multiple instances of ytdl-sub being able to download for a subscription

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#154]
Often I will be manually using ytdl-sub while the cron job is executing. The same subscription begins downloading twice which easily causes issues. We should implement some kind of file-lock

**Comment by funar** [comment]
You can accomplish this today in the shell script you use to launch the process like:

```
#!/bin/bash

exec {lock_fd}>/tmp/ytdl-sub.lock || exit 1
flock -n "$lock_fd" || { echo "ERROR: flock() failed." >&2; exit 1; }

ytdl-sub --config=/config/config.yaml sub /config/subscriptions.yaml

# This next line is not required as the lock will be removed once this shell exits.
flock -u "$lock_fd"

```

**Comment by jmbannon** [comment]
Nice workaround. I'd like to build this into the app itself, and have it lock reside in the working directory

**Comment by funar** [comment]
Thanks! For sure, it should be in the app.  This is just a quickie for anyone interested.  I use it anytime I have a task run that I don't want duplicity on.

**Comment by jmbannon** [comment]
Thanks @funar for your script, was a great starting point on how to properly implement this!
