### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by Code-Slave** [jmbannon/ytdl-sub#158]
I have looked at the docs. Is there a way to rate limit downloads so I dont break the 750gb barrier? I usually limit to 8mbps as some of the channels i hoard are quite large. 

Secondly what video /audio settings are used? I need to optimize for Apple TV 1080p mp4. With option for 4k

Thanks

**Comment by jmbannon** [comment]
Hi @Code-Slave , unfortunately there is no counter for measuring total download.

For format settings,  it uses ytdlp defaults. You can set ytdlp args here to change them:
https://ytdl-sub.readthedocs.io/en/latest/config.html#ytdl-options

**Comment by Code-Slave** [comment]
Ok ill look there. Rate limiting definitely exists in yt-dlp. Ive used it in all my scripts. In that config area will it pass through any valid options?

**Comment by jmbannon** [comment]
Correct, it's a direct passthrough to set any yt-dlp arg. They differ slightly since its the api and not the CLI args. There's a link in the docs I linked above that point you to their API docs
