### ISSUE TITLE
PLaylists

### ISSUE THREAD

**Issue by Code-Slave** [jmbannon/ytdl-sub#162]
Got channel archiving working well. What is the channel strategy mean for playlists? If im trying to have it named similiar to tv shows do i basically keep config the same and just change the strategy?

ex: i have a playlist (favorites) thats basically all about maintenance for my tractors and mowers. just looking hopw to build config.

my current config is slightly tweaked from the example wiki.

**Comment by Code-Slave** [comment]
btw. love the app. Ive been struggling to get my yt archive in jellyfin. This works perfectly. Now i have to dl 4-5 tb for like the 6th time

**Comment by jmbannon** [comment]
@Code-Slave I would set it up like this: https://github.com/jmbannon/ytdl-sub/wiki/6.-Modifying-Your-Config-for-Your-Media-Player#updating-our-configs

Have youtube videos be your base preset, then have playlists and channels inherit from it. The playlist download strategy could either use upload dates for episode ordering or playlist index:
https://ytdl-sub.readthedocs.io/en/latest/config.html#ytdl_sub.entries.variables.youtube_variables.YoutubeVideoVariables.playlist_index

**Comment by jmbannon** [comment]
For the season, I'd set it to a hardcoded string like 'Season 1' since playlist vids can contain many years
