### ISSUE TITLE
Video descriptions

### ISSUE THREAD

**Issue by Code-Slave** [jmbannon/ytdl-sub#166]
looking at my nfo files the video descriptions arent save just video title. Did i miss a config option or something?

**Comment by Code-Slave** [comment]
nvm

plot: "{description}" in nfo area

**Comment by Code-Slave** [comment]
now i need to wait for meta data refreshes as im not downloading again 4k videos

**Comment by jmbannon** [comment]
Also a hack you could do @Code-Slave  to update NFOs is create a new subscription, set `ytdl_options.format` to be really low-quality so it's quick to download, set `output_options.file_name` to something different so you can delete it later, and run to recreate NFOs

**Comment by Code-Slave** [comment]
Hmm thanks for the hint re downloading. Ill look at it. Im using jellyfin so the save should not be needed right?

**Comment by jmbannon** [comment]
@Code-Slave Right, `kodi_safe` is not needed for JF
