### ISSUE TITLE
Create a Sponsorblock plugin

### ISSUE THREAD

**Issue by Code-Slave** [jmbannon/ytdl-sub#167]
Possibly support the sponsorblock api. Tubearchivist has it implemented. Just wondering feasability they also support external up/downvotes might help with ratings

**Comment by jmbannon** [comment]
See https://github.com/jmbannon/ytdl-sub/issues/98 for how you can set ytdl_options for sponsorblock

**Comment by jmbannon** [comment]
Ideally it would be nice to have a plugin that makes setting these args easier and documented. Going to reuse this issue as the feature request.
