### ISSUE TITLE
Plugin to embed metadata into video files

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#168]
For plex support - plex reads the `title` field from a video container's embedded data

**Comment by Code-Slave** [comment]
would it make sense to download the metada as a json via the built in ytdlp support then parse it offline? that way if someone changes what metadata they want to associate it easier to parse json local instead of online calls again?

**Comment by jmbannon** [comment]
> would it make sense to download the metada as a json via the built in ytdlp support then parse it offline? that way if someone changes what metadata they want to associate it easier to parse json local instead of online calls again?

That was one idea I had for https://github.com/jmbannon/ytdl-sub/issues/155 - Let's move the discussion there.

This issue is a separate issue - it has to do with writing video container embedded fields. yt-dlp does with with `--metadata` I think. But the problem with that is it wouldn't support source/override variables, so we have to write it ourselves.
