### ISSUE TITLE
Channel/playlist descriptions as source variables

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#171]
Let's add a new source variable called `{source_description}`

- For videos in a playlist, this will be the playlist description.
- For videos in a channel, this will be the channel description.
- For single videos, fall back to the video description

**Comment by Code-Slave** [comment]
So this can be used for the show description in the info? I am assuming thats the usecase

**Comment by jmbannon** [comment]
Yep, exactly
