### ISSUE TITLE
Youtube subtitle download not working for playlists

### ISSUE THREAD

**Issue by vaarnio** [jmbannon/ytdl-sub#174]
Subtitles download fine for individual videos, but for some reason downloading subtitles for playlists produces a KeyError. Maybe 'requested_subtitles' variable isn't being applied to YoutubePlaylistVideo entries for some reason?

[playlist dl command output.txt](https://github.com/jmbannon/ytdl-sub/files/9331909/playlist.download.output.txt)
[config.yaml.txt](https://github.com/jmbannon/ytdl-sub/files/9331920/config.yaml.txt)
[error_log.txt](https://github.com/jmbannon/ytdl-sub/files/9331918/error_log.txt)

**Comment by jmbannon** [comment]
I think it's a yt-dlp issue - doesn't download subtitles for vids in a playlist or channel.
