### ISSUE TITLE
Improve override error handling

### ISSUE THREAD

**Issue by Code-Slave** [jmbannon/ytdl-sub#181]
In my subscription I forgot to add the channel name override. I think it would be helpful to add some error check or a defaultname from the channel if. Id rather it error and say hey you missed channel name override dummy if possible

**Comment by jmbannon** [comment]
You can do this by using a different variable name like `custom_channel_override` in your preset, and _NOT_ set the override variable in the preset. Then in your subscription, if you do not set it, it will error.
