### ISSUE TITLE
Error ofter download on grabbing poster/thumbnail

### ISSUE THREAD

**Issue by Karasune-Kurohane** [jmbannon/ytdl-sub#211]
download runs perfectly fine, videos and infos are there but no thumbnails.
that problem happens not on all channels.

i would mind doing it afterwards by hand but it stops the procces compleatly and dont process the entrys in the subscription.yaml witch come afterwards.

[config.yaml.txt](https://github.com/jmbannon/ytdl-sub/files/9483490/config.yaml.txt)
[subscriptions.yaml.txt](https://github.com/jmbannon/ytdl-sub/files/9483491/subscriptions.yaml.txt)
[ytdl-sub.3ip3p1li.txt](https://github.com/jmbannon/ytdl-sub/files/9483492/ytdl-sub.3ip3p1li.txt)

**Comment by jmbannon** [comment]
Will fix this sometime this week. Thanks for the report!
