### ISSUE TITLE
Could not find thumbnail error

### ISSUE THREAD

**Issue by blitzdakka** [jmbannon/ytdl-sub#214]
Config: https://pastebin.com/Yc31ug2F
Subs: https://pastebin.com/0xp57eNz
Debug log: https://pastebin.com/MzB57Vdk

Have successfully downloaded other videos for this channel, but getting a thumbnail error now.

**Comment by jmbannon** [comment]
Thanks for the report! It fails trying to download the channel's thumbnail/banner. Closing since this is a duplicate issue: https://github.com/jmbannon/ytdl-sub/issues/214
