### ISSUE TITLE
Handle cases where a source variable value contains a `{variable_like}` string

### ISSUE THREAD

**Issue by blitzdakka** [jmbannon/ytdl-sub#215]
Config: https://pastebin.com/Yc31ug2F
Subs: https://pastebin.com/0xp57eNz
Debug log: https://pastebin.com/vZLDTutH

Note this is the same config/subs file as #214 so you'll need to comment out the antonhand sub to reproduce this error.

Have successfully downloaded other videos for this channel, but am now getting an error related to the tags.

**Comment by jmbannon** [comment]
Thanks for the report, this is a very odd bug. I think it might be from a description actually containing `{variable_names}`, then ytdl-sub thinks its a variable to fill in, but then doesn't exist. I'll get around to reproducing it sometime this week

**Comment by jmbannon** [comment]
As a work-around, you could remove `plot: "{description}` from the NFO tags. In my experience with description in the plot, newlines aren't respected so its format looks ugly, and 90% of the the time it only links to channel merch or other things like their twitter/facebook/IG/etc. Personally, I'm going to remove it from my config

**Comment by blitzdakka** [comment]
Thanks, that work around definitely works! I use plex so found out after posting the the nfos are largely useless to me anyway haha.

**Comment by jmbannon** [comment]
Once you have YouTube vids showing in plex, mind sharing your config? Would be nice to have an official Plex config in the examples (I'm a Jellyfin/Kodi user)

**Comment by blitzdakka** [comment]
Yes I'm on the discord so I'll share it there when I'm done playing, it'll be pretty basic but should achieve what I was after.
