### ISSUE TITLE
Multi-genre support

### ISSUE THREAD

**Issue by mcarlton00** [jmbannon/ytdl-sub#216]
Add support for saving multiple user defined genres into the generated NFO files.  Adding a single genre is currently possible with the tags in a subscription:
```yaml
output_directory_nfo_tags:
  tags:
    genre: "Science"
```
However this only allows one genre (or multiple defined in a single string value, which is technically invalid and not able to be accurately picked up by all media programs).  (Sources: [kodi wiki](https://kodi.wiki/view/NFO_files/TV_shows) and [old kodi forum post](https://forum.kodi.tv/showthread.php?tid=40885), plus my own testing with Jellyfin.)  Unfortunately this isn't as straightforward as it seems initially.  The proper way to include multiple genres in a nfo file is with multiple headings.  ie:

```xml
<genre>Science</genre>
<genre>Engineering</genre>
```
This is somewhat tricky to handle in python since we're using a dict to store the tag values, and unlike xml a dict needs to have unique keys.  After a few hours of exploratory poking, the only somewhat reasonable way I've found to handle this is to store all the requested genre values in a single dict value and have the [to_xml function](https://github.com/jmbannon/ytdl-sub/blob/3e801c56eb63335a9e636ff7756c9ed02904a4f5/src/ytdl_sub/utils/xml.py#L62-L84) check for a list of values and handle the multiple headings at generation time.  Obviously this also introduces the question of whether to make it a delimited string and split it at generation time or to pass a full string value all the way through from the config file, which would require additional pieces to the validators as far as I can tell, but I got a little fuzzy around there.

**Comment by jmbannon** [comment]
I knew this would come up eventually, lol. I'm thinking we can include duplicate tag keys by having something like this:

```
nfo_tags:
  genre:
    - drama
    - comedy
```
or
```
nfo_tags:
  genre:
    - attributes
         name: hello
      tag: drama
    -  attributes
        name: hello2
     tag: comedy
```

**Comment by jmbannon** [comment]
We should not use delimited strings. We do similar logic today in the NfoTagsOptions class by checking the type of the nfo tag, whether it's a string (single tag) or dict (attribute tag).

You seem pretty savvy in python, would you want to take this task? ;)

**Comment by mcarlton00** [comment]
Yeah, it's a fairly simple use case that's followed by some ugly code, so I probably would've skipped it initially as well :sweat_smile:.  Delimited strings is the easy/hacky "make it work" way, but yaml lists and passing them through is definitely the more correct way.  I would personally default to the
```
nfo_tags:
  genre:
    - drama
    - comedy
```
method of definitions, rather than being forced to rely on the more verbose attributes method.  It may end up making sense to use the attributes internally regardless to help with the unique key issue, but it's hard to say without being more familiar with the guts.

> You seem pretty savvy in python, would you want to take this task?

I'm just a monkey slapping at a keyboard to keep some Jellyfin clients alive.  I tried, but frankly all of the validator code just turns into spaghetti and makes my eyes cross as soon as I try to find my way through it.  Otherwise you'd have a shiny PR instead of a feature request.  And unfortunately I definitely don't have time to sort it out in the near future.

**Comment by jmbannon** [comment]
Was way harder than I thought to implement this, but alas, it's done! Just pushed so give it about 10m for the `latest` docker image to update. Supports 
```
tags:
  genre:
    - drama
    - comedy
``` 
now for both nfo_tags and output_directory_nfo_tags
