### ISSUE TITLE
Regex should be processed before downloading the video

### ISSUE THREAD

**Issue by serenewaffles** [jmbannon/ytdl-sub#219]
To save time and bandwidth, it would be great if regex filters were applied between downloading the metadata and downloading the video.

**Comment by jmbannon** [comment]
Going to close this in favor of using the match filters plugin: https://ytdl-sub.readthedocs.io/en/latest/config.html#match-filters
This can perform regex matching and filter any videos before any metadata is downloaded.

ytdl-sub's regex plugin can operate on variables that aren't available until after downloading, i.e. splitting a video by chapters and performing regex on the chapter title. Therefore I think it's best to keep it as-is.

**Comment by jmbannon** [comment]
Turns out match-filters aren't great. Reopening and fixing
