### ISSUE TITLE
brackets in title cause validation error

### ISSUE THREAD

**Issue by Code-Slave** [jmbannon/ytdl-sub#258]
IE

ytdl-sub:downloader] Downloading 198/436 Catch and Cook BIG TROUT {GRAPHIC} GUT, CLEAN & FILLET | Cook on a STICK

Validation error in taoutdoors.nfo_tags.tags.title: {variable_names} must start with a lowercase letter, should only contain lowercase letters, numbers, underscores, and have a single open and close bracket.

**Comment by jmbannon** [comment]
Was fixed in https://github.com/jmbannon/ytdl-sub/pull/231
