### ISSUE TITLE
Issue with Archive

### ISSUE THREAD

**Issue by crospa91** [jmbannon/ytdl-sub#262]
Hey there! First of all thanks for the Code, it's working great!

I have just a small issue. 
I've tried to download a full channel and the app completely went bananas. 
Today I've restarted the docker container and I've noticed the archive file inside the channel folder is not readable, or at least, if I try to open it, both via docker or via the host PC I the text edit (vim and nano) get stuck forever in "Reading File..." and this prevent any future cron to process the downloads.

Have you ever experienced something like this? 

Any tips on how to solve it?

**Comment by jmbannon** [comment]
I haven't seen this issue. Any logs on when it went bananas?

Might be best to delete the file and channel's folder, restart from scratch.

**Comment by crospa91** [comment]
If you can point me to a log file I will be more than happy to show you.
Overnight I’ve re-downloaded the whole channel and trying again now to run the command, to see if it can just check for new videos or it get stuck again opening the archive .json file.

the issue is still there tho.

either the .json is so huge that the app take too long to re-open it and then crashes cause Linux kill the process for it… i don’t know. I can share you the .archive file here if you want so you can try yourself to see what happen?

**Comment by crospa91** [comment]
I did receive an error finally after a few hours that the scripts was running

```

[ytdl-sub] Beginning subscription download for charlotte_dobre
[ytdl-sub] An uncaught error occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ytdl_sub/main.py", line 28, in main
    _main()
  File "/usr/lib/python3.10/site-packages/ytdl_sub/main.py", line 19, in _main
    ytdl_sub.cli.main.main()
  File "/usr/lib/python3.10/site-packages/ytdl_sub/cli/main.py", line 150, in main
    transaction_logs = _download_subscriptions_from_yaml_files(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/cli/main.py", line 53, in _download_subscriptions_from_yaml_files
    transaction_log = subscription.download(dry_run=args.dry_run)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 248, in download
    with self._subscription_download_context_managers():
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 135, in _subscription_download_context_managers
    with (
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 116, in _maintain_archive_file
    self._enhanced_download_archive.prepare_download_archive()
  File "/usr/lib/python3.10/site-packages/ytdl_sub/ytdl_additions/enhanced_download_archive.py", line 510, in prepare_download_archive
    self._load()
  File "/usr/lib/python3.10/site-packages/ytdl_sub/ytdl_additions/enhanced_download_archive.py", line 477, in _load
    self._download_mapping = DownloadMappings.from_file(
  File "/usr/lib/python3.10/site-packages/ytdl_sub/ytdl_additions/enhanced_download_archive.py", line 165, in from_file
    entry_mappings_json = json.load(json_file)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
OSError: [Errno 5] I/O error
[ytdl-sub] Please upload the error log file '/tmp/ytdl-sub.9ira9b9_' and make a Github issue at https://github.com/jmbannon/ytdl-sub/issues with your config and command/subscription yaml file to reproduce. Thanks for trying ytdl-sub!

```

**Comment by jmbannon** [comment]
Interesting... how big is the file? I don't think it's size related but might give us a clue. Hard to say exactly what's going on, errno 5 is very ambiguous

**Comment by crospa91** [comment]
The file is approx 234byte

What do you suggest me to do??

**Comment by jmbannon** [comment]
So when you say you tried outside the system, do you mean an ext4 FS? That is what I use and test on.

Also the archive file is only ever opened to immediately read/write to, then closed right after.  There's also users who have downloaded dozens of TBs using ytdl-sub so I know it can handle large channels. I'm thinking this is something on your end.

**Comment by jmbannon** [comment]
For a next step I'd say run ytdl-sub on ext4, do not have unionFS anywhere adjacent to ytdl-sub

**Comment by crospa91** [comment]
Let me try to run it directly on the remote folder instead of passing via the unionfs.
eventually there isn't a way to just store this archive file in a separate directory? so we can just save this separated from the whole files on the unionfs that are currently working perfectly?

**Comment by jmbannon** [comment]
There's no way currently - it will reside at the root of the specified output directory.

**Comment by crospa91** [comment]
Nothing, even having everything saving on the disk directly create the same identical behaviour. 
My disk are actually formatted in XFS not Ext4, you think that might be the problem?

**Comment by jmbannon** [comment]
Could be. Maybe a permission issue? Or hardware issue? Google the `errno5` error code and you'll see it can be so many different things. I think it's safe to say it's not on the ytdl-sub side of things so I'm going to close this out. Good luck fixing it, sorry if it doesn't work out. Worst case you could buy a raspberry pi and use that for ytdl-sub
