### ISSUE TITLE
how do you limit the amount of media downloaded from a subscription? 

### ISSUE THREAD

**Issue by neu-ma-tic** [jmbannon/ytdl-sub#263]
if I download from a channel with 1000 videos, i dont want all 1000, but I do want future videos. is there a way to limit the amount?

**Comment by jmbannon** [comment]
Yes, see https://ytdl-sub.readthedocs.io/en/latest/config.html#date-range

Set `after` to something like `today-2months` to only grab the last 2 months worth of vids
