### ISSUE TITLE
Plex: Download mp4/m4a directly from youtube vs converting via ffmpeg

### ISSUE THREAD

**Issue by BurroHen** [jmbannon/ytdl-sub#280]
I noticed the conversion from webm to ffmpeg greatly increases the time to download and save files.   If we use something like:

```
    ytdl_options:
      format: "bv[ext=mp4]+ba[ext=m4a]"
```
This will download the best quality mp4 and audio from youtube and combine them, cutting out the conversion process.  There may still be some fine-tuning of that format, but that seems to be working well for me.

**Comment by jmbannon** [comment]
Thanks for the suggestion @BurroHen , I think I will add this.

**Comment by Code-Slave** [comment]
I use this for 1080p

format: "bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"

taken from a reddit thread for ios best settings
