### ISSUE TITLE
Best way to download playlists

### ISSUE THREAD

**Issue by henryb3** [jmbannon/ytdl-sub#282]
What would be the current configuration to use to download a playlist?   I see two different ways I would like to do so. 

1. Playlist as a channel (playlist and all of the videos on it become a single show).
3. Playlist of videos in channels (playlist downloads videos across multiple channels and creates those videos in those multiple channels).

**Comment by jmbannon** [comment]
Hello again @henryb3

For 1: You can use the tv show preset on ANY url, including playlists or other websites like bitchute
For 2: See the 'collection' preset: https://ytdl-sub.readthedocs.io/en/latest/presets.html#tv-show-collection It is aimed at creating a TV show from multiple URLs, including many playlists or many channels

FYI I am planning to make the interface simpler for these TV show presets. Might be worth waiting a little bit. You should hop in our discord, your input would be appreciated :)
