### ISSUE TITLE
Option for removing content when x video files, or age

### ISSUE THREAD

**Issue by psyciknz** [jmbannon/ytdl-sub#296]
I currently use podsync (which uses ytdl) to get youtube videos down and create them into a podcast.  But I've written a plex metadata agent to pull in the files to plex.

One feature it has it the ability to keep x number of episodes.

I've stumbled across your project when looking for a way to migrate this across to jellyfin.  Is there an option for allowing me to only keep episodes of a certain age, or would I handle that externally.  Seems most people want to keep a permanent library of content.  Whereas I just prefer to watch in something like plex/jellyfin as they respect episode order and watched history.

**Comment by jmbannon** [comment]
This feature exist here: https://ytdl-sub.readthedocs.io/en/latest/config.html#ytdl_sub.config.preset_options.OutputOptions.keep_files_after

Set it to something like:
```
output_options:
  keep_files_after: "today-2weeks"
```
to keep the latest two weeks worth of content
