### ISSUE TITLE
autonumber

### ISSUE THREAD

**Issue by csjoh** [jmbannon/ytdl-sub#300]
When I download channels manually, I can specify `--autonumber-start 1 -o "%(channel)s - S%(upload_year)sE%(autonumber)s - %(title)s.%(ext)s"` and have sequentially increasing episode numbers. Some of the channels I download are tracked in Sonarr, and Sonarr expects "standard" episode numbers.

Is there a way to have the "autonumber" feature of yt-dlp work?

**Comment by jmbannon** [comment]
No support for autonumber at this time but should be easy to add

**Comment by jmbannon** [comment]
Forgot to ask @csjoh , why use Sonarr if ytdl-sub can generate the NFO for you? I think the only thing you'd miss is maybe a better description of the episode

**Comment by jmbannon** [comment]
Closing this since autonumber wouldn't work well for successive downloads and for how ytdl-sub is structured for formatting TV shows
