### ISSUE TITLE
Add special case treatment for ytdlp match_filter options

### ISSUE THREAD

**Issue by Behem07h** [jmbannon/ytdl-sub#314]
In ytdlp python, this is how match_filter is formatted in ytdlp-opts:
'match_filter': yt_dlp.utils.match_filter_func("duration<3600" )
This is currently (afaik) not possible to enter in ytdl-sub as part of a custom preset, as it requires a reference to the yt_dlp.utils.match_filter_func function. 
I propose that match_filter should be treated as a special case, where only the function input is required e.g match_filter = "duration<3600"

**Comment by Vorror** [comment]
I'm hitting this exact issue. Is there any workaround?

**Comment by jmbannon** [comment]
This seems to be a frequently requested feature. I will work on this soon

**Comment by jmbannon** [comment]
Feature is in! See https://ytdl-sub.readthedocs.io/en/latest/config.html#match-filters for docs
