### ISSUE TITLE
Add .m3u playlist file support

### ISSUE THREAD

**Issue by Behem07h** [jmbannon/ytdl-sub#315]
This would allow for a smart playlist that updates to include newly downloaded media, but also remembers which media the user has opted to remove from the playlist
this is a distinction from the conventional concept of a smart playlist as many implementations of smart playlists are effectively a function to selectively play media based om file tags

**Comment by jmbannon** [comment]
Would the playlist match the download archive file? Or be different?

**Comment by funar** [comment]
I don't mean to hijack the suggestion, but it might be far better to create m3u files of downloaded media based YT playlists instead.

**Comment by jmbannon** [comment]
Not sure what that means either, lol. I see two different methods:

1. Have the playlist .m3u rewritten on each download invocation, any video in the download archive will be in this playlist (so one playlist file per subscription)
2. Appends to the playlist .m3u file (multiple subscriptions could append to this)

**Comment by funar** [comment]
To clarify, my alternate suggestion is: When a channel is synced, if the channel has YT playlists associated with it, grab the playlists as well.  Any videos that have been downloaded could then be added to local versions of those playlists.

If a YT creator has several series of videos on their channel in episodic format, but also create playlists to separate those videos, this would make it a lot easier to watch them, in order, offline.

**Comment by jmbannon** [comment]
Got it, that makes sense. This might be doable w/just a plugin that writes m3u files.

I'll soon be making docs and a new release on the new download strategy that I think @Behem07h is familiar with, which allows specifying multiple URLs in the download.

I think for your guys' case, you could specify two URLs:
1. The channel (which includes ALL videos)
2. The channel's playlist vids (i.e. https://www.youtube.com/user/videogamedunkey/playlists)

Bottom-most has priority, so if a vid is in a playlist, it will use that metadata (which will include the playlist name, index, etc). Then, we can use that to append it to a m3u file titled as the playlist.

One thing I'm not sure how yt-dlp handles is if a video appears in multiple playlists.

**Comment by Behem07h** [comment]
damn i didnt get any of the email notifs for github :/
What i meant is for newly downloaded media to be appended to a playlist, not have a playlist thats rewritten every time to match download archive - reasoning being that a playlist that matches download archive is equivalent to playing by folder, whereas a playlist that gets new media appended to it can be manually edited without fear of said edits being overwritten every time ytdl-sub is run
Anyhow, i see that the music_audio_from_videos.yaml example has mention of a song playlist, but it's marked as todo. Is this currently something functional or is it left in for a future update?

As for ytdlp dealing with the same video appearing in multiple playlists, I can confirm that maintain_download_archive: True in your output options prevents the video from being downloaded, since the video retains the same ID even if its being downloaded from a different playlist. not sure if the same happens without this setting

**Comment by jmbannon** [comment]
Got it, yeah a naive append should be pretty easy. Let's do that for an MVP

re `music_audio_from_videos.yaml`, I need to update that - everything is there for it to work. Just need to set the album override to `playlist_title`

It should be the same even without maintain download archive, but they'd redownload on another invocation

**Comment by jmbannon** [comment]
Going to close as most likely won't do
