### ISSUE TITLE
"Address not available" and working directory not empty

### ISSUE THREAD

**Issue by Glynax** [jmbannon/ytdl-sub#338]
Tried 3 times, it dies on the same video from gamechop (https://youtu.be/2DVpys50LVE)
Deleting the empty gamechops dir it leaves in working directory does not fix the error.

[ytdl-sub.txt](https://github.com/jmbannon/ytdl-sub/files/10037682/ytdl-sub.txt)

**Comment by jmbannon** [comment]
"Address not available" is common from being throttled. The working directory taking a dump should be fixed though

**Comment by jmbannon** [comment]
Working directory issue should be fixed by https://github.com/jmbannon/ytdl-sub/pull/379
