### ISSUE TITLE
Playlist not updating

### ISSUE THREAD

**Issue by squidrpi** [jmbannon/ytdl-sub#351]
Have playlists but if I add videos to the playlists they do not get updated. 

**config.xml**

configuration:
  working_directory: '/tmp/.ytdl-sub-downloads'

presets:
  only_recent_videos:
    date_range:
      after: "today-{download_range}"

    ytdl_options:
      break_on_reject: True
      format: "bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"

    overrides:
      download_range: "3months"

  tv_show:
    preset:
      - "jellyfin_tv_show_by_date"
      - "season_by_year__episode_by_month_day"

    overrides:
      tv_show_directory: "/tv_shows"  # Replace with desired directory

    output_options:
      maintain_download_archive: True
  
  tv_playlist:
    preset:
      - "jellyfin_tv_show_collection"
      - "season_by_collection__episode_by_year_month_day_reversed"
      - "collection_season_1"

    ytdl_options:
      break_on_reject: True
      format: "bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"

    overrides:
      tv_show_directory: "/tv_playlist"

    output_options:
      maintain_download_archive: True

**playlists.yaml**

musicplaylist:
  preset:
    - "tv_playlist"
  overrides:
    tv_show_name: "Music"
    tv_show_genre: "Music"
    collection_season_1_url: "MYPLAYLIST"
    collection_season_1_name: "Music Playlist"

run command `ytdl-sub --config=/config/config.yaml sub /config/playlists.yaml`

**Comment by jmbannon** [comment]
Can you try running with `ytdl-sub --config=/config/config.yaml sub /config/playlists.yaml` and upload the output? That should better tell us what's going on

**Comment by squidrpi** [comment]
This appears to break it:

`[ytdl-sub:yt-dlp] [youtube:tab] Playlist Music: Downloading 1 videos of 38
[ytdl-sub:yt-dlp] [download] i want to die has already been recorded in the archive
[ytdl-sub:downloader] ExistingVideoReached, stopping additional downloads
[ytdl-sub] No files changed for musicplaylist`

I've set the following in my tv_playlist preset 
`ytdl_options:
      break_on_existing: False
`
and the downloads work now.

Maybe an idea to add some examples for Youtube playlists.

**Comment by jmbannon** [comment]
Are you adding videos to the beginning or end of the playlist? You should add at the beginning because metadata downloads start with the most recent (first) vid, and will stop once it hits an existing video.

It seems backwards, but that's how channel vids are treated - as playlists where most recent video has playlist_idx of 1

**Comment by jmbannon** [comment]
`break_on_existing: False` also works but will waste a little bit of time fetching metadata for vids already downloaded

**Comment by squidrpi** [comment]
YouTube default is to add to end. Not a problem on break_on_existing as I only update these playlists once a day.

**Comment by jmbannon** [comment]
Got it, good to know!
