### ISSUE TITLE
Include archive file contents in dry-run output

### ISSUE THREAD

**Issue by Vorror** [jmbannon/ytdl-sub#361]
### Request
Is it possible to add an option that modifies the behavior of the `--dry-run` command? 

Maybe something called: `--create-download-archive` which generates the same archive file that _would_ have been generated if the files were actually downloaded?

### Usecase

If the archive file is accidentally deleted/lost, I would like to be able to re-run my subscription without actually downloading all the music/videos/files again.

I know we have filtering with `download_range` but that's really not what I want.

### Extra benefits

There are also other benefits. If the download archive format ever changes, it gives us the ability to "forward upgrade" our manifiest files.

**Comment by jmbannon** [comment]
Interesting idea, though I'm not really sold on the use-case. Why would the archive file get lost or deleted, but the videos themselves?

I think https://github.com/jmbannon/ytdl-sub/issues/155 would be a better approach and more scalable to other use cases. Basically my vision is to have a download strategy that only looks at local files and yt-dlp info.json files. That could rebuild the download archive

**Comment by Vorror** [comment]
@jmbannon I added a second use case above.

re: lost archive:

It's unlikely, but the download archive is technically hidden by default(".archive") and it's always possible one day that I might accidentally delete or not transfer over the archive file during storage transfers or backup process. This is technically a user-error but It gives an easy way to fix it.

I'm not too big of the `.nfo` idea since I don't want to have so many unrelated files for my music. NFO files make sense for video-based downloading, but not really for music-based downloads.

**Comment by jmbannon** [comment]
`.info.json`, not `.nfo`, but yeah I hear ya. Let's do this - in the dry-run output let's make it toggle-able to also include the download archive's full JSON that should be easily copy/paste-able

**Comment by Vorror** [comment]
@jmbannon That works for me! 
How would you handle `sub` which generates an archive per sub entry?

**Comment by jmbannon** [comment]
It will be like any file in the dry-run output: name the archive's file name and in the contents, dump the entire JSON that would be produced by performing the download

**Comment by Vorror** [comment]
Sounds like a good plan to me

**Comment by jmbannon** [comment]
We'll probably want to add this first: https://github.com/jmbannon/ytdl-sub/issues/288
The dry-run output already often consumes the entire terminal's max lines lol
