### ISSUE TITLE
add spotify playlist support by searching youtube music for a matching song

### ISSUE THREAD

**Issue by Behem07h** [jmbannon/ytdl-sub#363]
ytdlp only supports downloading spotify episodes and shows, however projects like https://github.com/spotDL/spotify-downloader are able to support playlist and track urls by searching youtube music for a matching song url.
This has an advantage over downloading the spotify music directly, which would require emulating the desktop client as seen in zspotify here https://github.com/yt-dlp/yt-dlp/issues/1368

**Comment by jmbannon** [comment]
This would require a pretty significant integration. That and there are many unknowns like how flexible their API is to, for example, only fetch the URLs. If I'm being honest it's too much work for something I'll never use. Going to pass but am open to someone else contributing this feature
