### ISSUE TITLE
File path input sanitisation and possible directory traversal

### ISSUE THREAD

**Issue by talkingseedling** [jmbannon/ytdl-sub#369]
ytdl-sub used: v0.5
If your file path includes {title} and the title of the video is something like "tutorial video 1/5", then the forward slash creates a new folder "tutorial video 1" and the video becomes a file within that folder "5.webm". Apart from not being the expected behavior, I imagine videos with "/../' in the title could be used for directory traversal.

**Comment by Vorror** [comment]
I think you should use `title_sanitized` instead and that would fix it.

**Comment by jmbannon** [comment]
which preset doesn't use title_sanitized ?

**Comment by jmbannon** [comment]
I think I misread the OP. @Vorror is correct in that you should use `_sanitized` variables for file names.
We can't sanitize the entire file path automatically because then we couldn't differentiate a directory `/` vs a `/` in the title.
