### ISSUE TITLE
Overrides with presets

### ISSUE THREAD

**Issue by talkingseedling** [jmbannon/ytdl-sub#370]
ytdl-sub used: v0.5
When using the below in the config file
presets:
  tv_show:
    preset:
      - "jellyfin_tv_show_by_date"
setting a custom override for file_name seems to not work. (the override for episode_plot does though).

**Comment by jmbannon** [comment]
You can find the overrides here: https://github.com/jmbannon/ytdl-sub/blob/master/src/ytdl_sub/prebuilt_presets/tv_show/episode.yaml#L33

Another way is to run with `ytdl-sub --log-level debug ...` and the entire config YAML should print. That will show which override variables do what
