### ISSUE TITLE
Ability to use different language titles/descriptions

### ISSUE THREAD

**Issue by squidrpi** [jmbannon/ytdl-sub#372]
Noticed that if a video description is in multiple languages it doesn't default to english. I don't see a setting to control this.

Example channel with both japanese and english descriptions but it only shows japanese (and title) in jellyfin.

[https://www.youtube.com/@CoupyChannel](url)

**Comment by jmbannon** [comment]
What does your config with subtitles look like?

**Comment by squidrpi** [comment]
Only the following:
coupynew:
  preset:
    - "tv_show"
    - "only_recent_videos"
  overrides:
    tv_show_name: "Coupy Channel"
    url: "https://www.youtube.com/@CoupyChannel"
    download_range: "12months"
  subtitles:
    embed_subtitles: True 

Subtitles work fine and are in English.

**Comment by squidrpi** [comment]
That's a misunderstanding of the issue, it's not a subtitle issue but descriptions and titles. Example below; the download uses the japanese title and description but on youtube there is an english title and description available. I've looked through the code but cannot figure out how this information is being retrieved.

abc@7ec29a22bd7b:/config$ ytdl-sub --showname "At Japan" --singleshow "https://www.youtube.com/watch?v=k2y09AAzZ68"
usage: ytdl-sub [-h] [-c CONFIGPATH] [--dry-run] [--log-level quiet|info|verbose|debug] {sub,dl,view} ...
ytdl-sub: error: argument subparser: invalid choice: 'At Japan' (choose from 'sub', 'dl', 'view')
abc@7ec29a22bd7b:/config$ ytdl-sub dl --showname "At Japan" --singleshow "https://www.youtube.com/watch?v=k2y09AAzZ68"
[ytdl-sub] Beginning CLI download
[ytdl-sub:downloader] Beginning downloads for https://www.youtube.com/watch?v=k2y09AAzZ68
[ytdl-sub:downloader] Downloading entry 1/1: 昼間から日本初の豪華な完全個室バスでまったり一人旅🥰🚌城崎から大阪まで3時間｜ラグリア号（LuxRea）
[ytdl-sub] Downloads for cli-dl-a64e806b:
Files created:
----------------------------------------
/tv_shows/At Japan
  .ytdl-sub-cli-dl-a64e806b-download-archive.json
/tv_shows/At Japan/Season 2022
  s2022.e091001 - k2y09AAzZ68-thumb.jpg
  s2022.e091001 - k2y09AAzZ68.mp4
    Embedded Chapters:
    Video Tags:
      date: 2022-09-10
      episode_id: 91001
      genre: ytdl-sub
      show: At Japan
      synopsis: https://www.youtube.com/watch?v=k2y09AAzZ68
      title: 2022-09-10 - 昼間から日本初の豪華な完全個室バスでまったり一人旅🥰🚌城崎から大阪まで3時間｜ラグリア号（LuxRea）
      year: 2022
  s2022.e091001 - k2y09AAzZ68.nfo
    NFO tags:
      episodedetails:
        aired: 2022-09-10
        episode: 91001
        genre: ytdl-sub
        plot: https://www.youtube.com/watch?v=k2y09AAzZ68
        season: 2022
        title: 2022-09-10 - 昼間から日本初の豪華な完全個室バスでまったり一人旅🥰🚌城崎から大阪まで3時間｜ラグリア号（LuxRea）
        year: 2022

**Comment by jmbannon** [comment]
I see, I'm not sure either tbh. I'll read into it

**Comment by jmbannon** [comment]
Update: Found out how:
```
  ytdl_options:
    extractor_args:
      youtube:
        lang:
          - "en"
```
needs to be a list

**Comment by jmbannon** [comment]
Added it to our FAQ as well: https://github.com/jmbannon/ytdl-sub/wiki/FAQ#it-is-downloading-non-english-title-and-description-metadata

**Comment by squidrpi** [comment]
Yes that works great, thanks!
