### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by Vorror** [jmbannon/ytdl-sub#374]
Reposting the original discord issue:

As far as I'm aware, for every subscription entry, ytdl-sub downloads metadata for every video and then downloads the video. And that process repeats for every subscription entry. Is it possible that the old metadata for previous subscriptions is still stored in memory? (i.e, array/dictionary) even though ytdl-sub has moved on?

Image(Aftering running for 12+ Hours):
<img width="616" alt="CleanShot_2022-11-27_at_22 45 222x" src="https://user-images.githubusercontent.com/3613230/204192660-ef44c427-25fa-442a-adb5-e7e3e03bb336.png">

Config + Sub Files:
[Archive.zip](https://github.com/jmbannon/ytdl-sub/files/10100400/Archive.zip)

**Comment by jmbannon** [comment]
The above PR should hopefully fix things. Going to leave this open until we verify the fixes

**Comment by Vorror** [comment]
After testing for 10ish hours, I'm not sure that this is resolved. 


After watching the memory usage increase slowly over the course of 10ish hours:
 
![CleanShot 2022-11-29 at 12 06 29 2](https://user-images.githubusercontent.com/3613230/204597726-816834fb-2c4b-4466-b7e7-55d699dc6d91.png)

**Comment by jmbannon** [comment]
1.27gb looks much better than 2.54gb. Was the entire 10 hours spent on a single subscription?

**Comment by Vorror** [comment]
> 1.27gb looks much better than 2.54gb. Was the entire 10 hours spent on a single subscription?

Yes, the 10 hours were spent on a single subscription.

But actually, I made a mistake in my second image. The first image I sent was from [Glances](https://nicolargo.github.io/glances/), and my first image was from Docker stats. The way the count memory is a bit different.

Here's a like-for-like image(from Glances):
![CleanShot 2022-11-29 at 15 12 08](https://user-images.githubusercontent.com/3613230/204638815-30c1556c-fd40-4366-8519-460b2618407e.png)

The actual difference between how they count memory aside(apps like (h)top and docker stats count memory differently), neither saw a decrease in memory usage.

**Comment by Vorror** [comment]
Actually, after triple checking, the memory did free itself after awhile. I'll check back in a few hours. If everything is good I'll close the ticket.

**Comment by jmbannon** [comment]
Another memory leak source I realized is we store the debug log's entirety in memory. I just had a job fail after running for a few days and I have ~200mb of logs. This could definitely be truncated.

**Comment by jmbannon** [comment]
I've been at a stable 700mb mem usage according to `top` while running for ~2 days doing split albums. I think it's safe to say most of the memory leak is fixed. The debug log could be optimized but it's negligible unless you're running on super-limited memory. Going to close this out.
