### ISSUE TITLE
Use LSIO cron Dockermod

### ISSUE THREAD

**Issue by bpoulliot** [jmbannon/ytdl-sub#384]
I kept getting errors at the start of ytdl-sub with a README.txt attempting to execute. The readme stated that scripts were in "legacy locations" and should be moved to...the same directory (/config/custom-services.d/)? This started after following the steps to automate downloads. An easier route to go than what's documented thus far is to use the [LSIO universal cron Docker mod](https://github.com/linuxserver/docker-mods/tree/universal-cron). This will create /config/crontabs which is slightly different than where things are documented now.

You can still use a run_cron script or each entry can be added to the /config/crontabs/abc file. Note that this folder still needs to be mapped to /etc/crontabs.

I may be missing a reason to use a custom services script versus this mod, but it seems to be working for me thus far. It might be a good idea to create a persistent log file that's rotated/truncated to help anybody who automates track down any lingering issues in a config that don't always rise to the top immediately.

**Comment by jmbannon** [comment]
I had the same issue when LSIO updated s6 and updated the wiki to reflect that. AFAIK the directory needs to be `/custom-services.d`, not in `/config`. Will look into the docker mod later though!

**Comment by jmbannon** [comment]
Looking more into, I think this mod uses s6 v2, whereas the instructions in the wiki follow s6 v3. The repo/branch seems pretty outdated. Going to close this in favor of the v3 version.
