### ISSUE TITLE
Split By Chapters breaks when chapter names contains multiple sets of parentheses

### ISSUE THREAD

**Issue by Vorror** [jmbannon/ytdl-sub#385]
When downloading this [video](https://www.youtube.com/watch?v=uTlR3Ica2ps)

The following files are generated:
![CleanShot 2022-12-03 at 19 15 26](https://user-images.githubusercontent.com/3613230/205468057-55062fc9-b294-41db-8613-0116dce5fa46.png)

The chapter list is the following:
```
Tracklist Nightcore :
00:00 (Nightcore) Cartoon - On & On (feat. Daniel Levi)
03:02 (Nightcore) Cartoon - Why We Lose (feat. Coleman Trapp)
06:09 (Nightcore) Vanze - Forever (feat. Brenton Mattheus)
09:49 (Nightcore) Krale - Frontier (ft. Jasmina Lin & Jay Christopher)
13:11 (Nightcore) Jim Yosef - Forces (feat. Ivan Jamile & Kédo Rebelle)
17:01 (Nightcore) Janji - Heroes Tonight (feat. Johnning)
20:02 (Nightcore) Jim Yosef - Can't Wait (feat. Anna Yvette)
23:01 (Nightcore) Ship Wrek & Zookeepers - Ark 
26:00 (Nightcore) Electro-Light & Jordan Kelvin James - Wait For You (feat. Anna Yvette)
29:28 (Nightcore)  JJD - Adventure
34:19 (Nightcore) Halvorsen - She Got Me Like
36:42 (Nightcore) Desmeon - Hellcat
40:27 (Nightcore) Rameses B - Beside You (feat. Soundr) 
44:46 (Nightcore) Axol - ILY
47:40 (Nightcore) ElementD - Fallin' (feat. Micah Martin) 
50:24 (Nightcore) Futuristik - Little Bit (feat. Sethh)
54:39 (Nightcore) IZECOLD - Close (feat. Molly Ann)
57:20 (Nightcore) Chime & Adam Tell - Whole
```

The broken file names are the ones with a double set of parentheses in their name.
![image](https://user-images.githubusercontent.com/3613230/205468122-6c5cb82e-fadd-446a-a0dc-50a42c56c0fb.png)

**Comment by jmbannon** [comment]
@Vorror Do you have anything else in your config? Testing this locally, I don't see the parenthesis issue with just the chapter timestamp/title extraction logic

**Comment by jmbannon** [comment]
Also verified it's not from sanitizing any source variables:
```
sanitize_filename('(Nightcore) Electro-Light & Jordan Kelvin James - Wait For You (feat. Anna Yvette)')
'(Nightcore) Electro-Light & Jordan Kelvin James - Wait For You (feat. Anna Yvette)'
```

**Comment by Vorror** [comment]
@Vorror Let me re-run and double check

**Comment by jmbannon** [comment]
@Vorror Looking closer, the chapter names themselves are missing the parenthesis, but the description itself includes them. Going to close this
