### ISSUE TITLE
Failed to download thumbnail id 'avatar_uncropped'

### ISSUE THREAD

**Issue by binarygeek119** [jmbannon/ytdl-sub#387]
i keep getting this error, not sure what i did wrong in the config. new to this app.

i tacked on .log to the name to be able to upload it to github.
[config.yaml.log](https://github.com/jmbannon/ytdl-sub/files/10149057/config.yaml.log)
[subscriptions.yaml.log](https://github.com/jmbannon/ytdl-sub/files/10149058/subscriptions.yaml.log)
[ytdl-sub.ioxmd9dg.log](https://github.com/jmbannon/ytdl-sub/files/10149059/ytdl-sub.ioxmd9dg.log)

**Comment by jmbannon** [comment]
It's a common issue that will resolve itself eventually. My guess is it's YouTube servers being flakey. Going to close
