### ISSUE TITLE
Add prebuilt presets for `playlist__new_vids_at_end` and `playlist__new_vids_at_beginning`

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#389]
If you try to make a playlist a TV show, it expects new vids to be in the beginning of the playlist.

If you want to iterate backwards (new vids at end of the playlist), add:
```
ytdl_options:
  playlist_items: "::-1"
```
in your preset or subscription

**Comment by jmbannon** [comment]
Also add
```
playlist_thumbnails:
  - name: "{tv_show_poster_file_name}"
    uid: "latest_entry"
```

**Comment by npawelek** [comment]
For whatever reason the syntax above did not function when attempting to reverse playlist order. I added `playlistreverse: True` and this worked as expected

**Comment by jmbannon** [comment]
Solved automatically by https://github.com/jmbannon/ytdl-sub/commit/017db953bf6285ee2f669c5ac87ecabb0df0d20b
