### ISSUE TITLE
"mediafile.FileTypeError: "file.mkv" not in a recognized format"

### ISSUE THREAD

**Issue by Behem07h** [jmbannon/ytdl-sub#399]
[log.txt](https://github.com/jmbannon/ytdl-sub/files/10336491/log.txt)

**Comment by Behem07h** [comment]
seems to be caused by something i added to my config file, but i'm not sure what

**Comment by jmbannon** [comment]
You're trying to add music tags to a video file

**Comment by Behem07h** [comment]
ah, that makes sense. is there any significant difference between video_tags and music_tags? i feel like a mention of the limitations and differences between the two (e.g music_tags only working on audio-only file types) should be added to the docs

**Comment by jmbannon** [comment]
Kinda - music_tags will translate the proper tag (e.g. artist) to the file format's expected tag, which differs across mp3, ogg, flac, etc. video_tags will write whatever you throw at it.

I agree, better docs + error message are needed.
