### ISSUE TITLE
Create Unraid App

### ISSUE THREAD

**Issue by Breakingx** [jmbannon/ytdl-sub#424]
Hey I would love to test this project! Would it be possible to publish it to the unraid AppStore?

**Comment by p5-f20w18k** [comment]
Would also love to have this on unraid, happy to help test

**Comment by orthanc42** [comment]
![Screenshot 2023-01-16 at 14-53-23 bombur_UpdateContainer](https://user-images.githubusercontent.com/13221583/212764465-d80008cf-1528-43fa-ab40-735a891c53a7.png)
if you are already running dockers, you can use this config or similar to get it setup w/o needing an actual listing in the unraid app store.

**Comment by nath2125** [comment]
quite helpful that you put that there. just made one my self!! cheers!

**Comment by nath2125** [comment]
what configuration do you have for the yt channels, as im heading to that stage of setting up configs and can see its got tvshow default templates unsure if should be done differently for youtube playlist and channel videos for plex

**Comment by jmbannon** [comment]
it's now a community app! https://unraid.net/community/apps?q=ytdl-sub#r
cc @Breakingx @p5-f20w18k @nath2125
