### ISSUE TITLE
Logging to docker output + persistent logging

### ISSUE THREAD

**Issue by HStep20** [jmbannon/ytdl-sub#439]
As it stands now, the program does not log to the docker output. While it seems fine, since it is meant to be run in the cmd, once an automation is set up, the user has no persistent logging to monitor and make sure everything is going well. Ive wanted to check in a few times on my multi-tb redownload, but cannot due to the lack of logs. 

With issue #438, Im now concerned that the things Ive downloaded in the last 36 hours straight its been running are not actually removing the Sponsorblock segments, even though the dry-run said it would do so. Having some insight into what is actually happening inside the container during a run would be great.

**Comment by jmbannon** [comment]
Very valid point. Logging really needs an overhaul. I have a few GH issues made to address this:
https://github.com/jmbannon/ytdl-sub/issues/288
https://github.com/jmbannon/ytdl-sub/issues/406
https://github.com/jmbannon/ytdl-sub/issues/431

As for logs not going to docker output, my cron job logs do:
![image](https://user-images.githubusercontent.com/10107080/218550065-01ce4a2a-f779-4678-a052-62f484b8ec86.png)

I'm using the cron automation described here: https://github.com/jmbannon/ytdl-sub/wiki/7.-Automate-Downloading-New-Content-Using-Your-Configs

But to your point, we should set up a persistent log directory. Ideally I'd like to make a dedicated folder and have each subscription write to its own log file w/the timestamp. Also if there is an error, append `.error` to the end of it

**Comment by jmbannon** [comment]
As for when I can get around to this, I'm not quite sure. Job and family has me working overtime so I've had to deprioritize ytdl-sub for the time being

**Comment by NickChristensen** [comment]
I followed the wiki you've linked, and I'm also not getting any relevant logs in the docker output. ytdl-sub works as expected, including via cron, but docker log output is essentially still empty:

```
[custom-init] Service files found in /custom-services.d
[custom-init] cron: service detected, copying...
[custom-init] cron: copied
cont-init: info: running /etc/cont-init.d/30-config
[migrations] started
[migrations] no migrations found
cont-init: info: /etc/cont-init.d/30-config exited 0
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1026
User gid:    100
-------------------------------------
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

Are you doing anything specific to direct cron output to `stdout`?

**Comment by jmbannon** [comment]
Persisted logging is added! https://ytdl-sub.readthedocs.io/en/latest/config.html#persist-logs
Will soon add the ability to automatically remove old logs. Closing this issue out

**Comment by clemwo** [comment]
> Will soon add the ability to automatically remove old logs. Closing this issue out

any news on this?   

Thank you so much for this great tool, I love it!!

**Comment by jmbannon** [comment]
@clemwo No progress on that, made an issue here though so I don't forget: https://github.com/jmbannon/ytdl-sub/issues/777
Glad you're enjoying the tool :slightly_smiling_face:
