### ISSUE TITLE
Multiple subscription files?

### ISSUE THREAD

**Issue by jacroe** [jmbannon/ytdl-sub#447]
I've only started using this yesterday[^1] and so don't know if this is already supported or mentioned in another issue somewhere (that I couldn't find with my own searching), but is it possible to have multiple subscription files that get imported into the main one? Something like:

```subscriptions.yaml
include:
 - "gamegrups_sub.yaml"
 - "markiplier_sub.yaml"
 - "starkid_sub.yaml"
```

Where the other .yaml files contain what would have been in a long list within `subscriptions.yaml` but now broken out by topic/creator. I've only got ~18 shows added so far and it's almost 200 lines of YAML, and I plan to add maybe another 50 shows. And it would be great if I could have a little more organization than me forcing myself to alphabetize by hand.

[^1]: It's been really interesting so far. I'm still learning all the options, but I can't wait to take full advantage of the presets and multiple inheritance.

**Comment by jmbannon** [comment]
You can run `ytdl-sub sub sub1.yaml sub2.yaml` , basically any number of subscription yaml files so long as they share the same config. Names of them can be anything
