### ISSUE TITLE
file_name beginning with a / causes files to fail to correctly populate their folder

### ISSUE THREAD

**Issue by Behem07h** [jmbannon/ytdl-sub#480]
`
output_options:
    output_directory: "/my_directory"
    file_name: "/{title_sanitized}.{ext}"
`
the files end up downloading into ytdl-sub's root folder, and fail to merge into the file format given in ytdlp's merge_output_format

this may not necessarily be a bug but nonetheless this is worth being added to documentation if it isnt, as it certainly isnt intuitive at first glance

**Comment by jmbannon** [comment]
The file name is relative to the output directory. Specifying `/` as the first character is explicitly saying 'put this at the root', which is ytdl-sub's root folder. I don't think docs would make that any more clear
