### ISSUE TITLE
Embedding chapters from comments crashes

### ISSUE THREAD

**Issue by tylerdak** [jmbannon/ytdl-sub#481]
Looks like ffmpeg is crashing due to missing subtitles despite yt-dlp previously reporting that there's "no subtitles to convert" anyway.

Download works, the crash happens in post-processing:
[insanely long crash log here, just skip to the end](https://github.com/jmbannon/ytdl-sub/files/10840100/ytdl-sub.8uh2wnfe.txt)

**Comment by tylerdak** [comment]
Here's an online version, will expire in 24 hours: https://ctxt.io/2/AACQJAT2Eg

**Comment by jmbannon** [comment]
The error is from adding chapters via comments. As a workaround you can disable that

**Comment by jmbannon** [comment]
@tylerdak were you running ytdl-sub in docker? Or some other environment? One possible cause is from an old ffmpeg version

**Comment by tylerdak** [comment]
Yes, was running via docker

**Comment by jmbannon** [comment]
> Yes, was running via docker

Okay definitely not an ffmpeg issue then. I found two issues actually from the vid in your logs. After this second PR is pushed, it should hopefully work

**Comment by tylerdak** [comment]
Cool, I'll keep an eye out for it. Thanks!

**Comment by jmbannon** [comment]
Should be live! Going to close the issue - please reopen if it still persists
