### ISSUE TITLE
Live TV channel support

### ISSUE THREAD

**Issue by webysther** [jmbannon/ytdl-sub#484]
How works for download a live TV channel?

Sample: 
Sky News - https://www.youtube.com/user/skynews/live
Euronews - https://www.youtube.com/user/Euronews/live

I tried to find any tool to detect the loop in video too...

**Comment by jmbannon** [comment]
My guess would be that it doesn't work - I've never tried it. I think you're better off pointing at their channel's videos since then you'd get proper titles, metadata, etc.

**Comment by webysther** [comment]
> 

Good idea,thanks!
