### ISSUE TITLE
How to refresh metadata of existing files without re-downloading them

### ISSUE THREAD

**Issue by tyzbit** [jmbannon/ytdl-sub#508]
How do I refresh the metadata of existing files without re-downloading them, for instance in the case of changing the embedded tags?

I've tried this (as well as deleting the archive file) according to my best guess from the `yt-dlp` docs:
```yaml
ytdl_options:
  embedded_metadata: true
```

**Comment by jmbannon** [comment]
Unfortunately this isn't supported at this time. The best workaround is to redownload the video

**Comment by tyzbit** [comment]
Thanks for the response. Feel free to close this issue or convert it over to a feature enhancement request for that functionality.

**Comment by nullicist-aakash** [comment]
Hi, is this supported now? I downloaded the media files but not happy with the long description in the jellyfin. I want to clean the description in jellyfin view and simply replace it with youtube link, but it seems that I either need to parse nfo files on my own and "fix" them, or redownload the media files again.

**Comment by jmbannon** [comment]
@nullicist-aakash that operation does not require downloading new metadata. Alter your config/subscription setup, and then run --update-with-info-json
