### ISSUE TITLE
Push docker images to hub docker in github workflow

### ISSUE THREAD

**Issue by webysther** [jmbannon/ytdl-sub#509]
On synology docker app ghcr.io not working because a limitation, any chance to push the tag in a hub docker too?

**Comment by webysther** [comment]
If you want automated cost money, but push manual is free. Yeah, the changed of last 2 years on docker hub was sad.

**Comment by jmbannon** [comment]
Going to close, it indeed costs money and I don't have time for manual pushes. Doing so would up making folks versions out of date because I'll forget lol

**Comment by webysther** [comment]
From github flow you can push to hub docker in the pipeline, this is a meant about manual.

**Comment by webysther** [comment]
This is a one extra line on your release https://github.com/jmbannon/ytdl-sub/blob/master/.github/workflows/release.yaml to make a docker push in the same way. Automatic was a old feature on hub docker to start build when you publish a tag.

**Comment by webysther** [comment]
Here is a Github step-by-step: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub
