### ISSUE TITLE
urlopen error [Errno 99] Address not available

### ISSUE THREAD

**Issue by fredamn76** [jmbannon/ytdl-sub#537]
Ytdl-sub cannot download any content from youtube. 
`WARNING: [youtube:tab] <urlopen error [Errno 99] Address not available>`

Can someone point me in the right direction?

Docker-compose service: https://pastebin.com/4nnZkHtG
Full debug output: https://pastebin.com/KRfzDA9T
config.yaml: https://pastebin.com/LsdmL4cZ
subscriptions.yaml: https://pastebin.com/15sEjMPp

**Comment by jmbannon** [comment]
The example playlist URL no longer exists. I will update that. Try again with any other playlist URL

**Comment by fredamn76** [comment]
Thank you for fast response!

I change the url to playlist. Still no go.
https://www.youtube.com/playlist?list=PLoNeexaMKxIbDvvDJ-g7tlkJycFwsGLxg

**Comment by jmbannon** [comment]
can you try `ping 8.8.8.8` within the docker container? Seems like you have no internet access

**Comment by fredamn76** [comment]
Result om ping.

root@e4c0364ef13e:/# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=117 time=12.324 ms
64 bytes from 8.8.8.8: seq=1 ttl=117 time=12.132 ms
64 bytes from 8.8.8.8: seq=2 ttl=117 time=12.229 ms
64 bytes from 8.8.8.8: seq=3 ttl=117 time=12.568 ms
64 bytes from 8.8.8.8: seq=4 ttl=117 time=12.172 ms
64 bytes from 8.8.8.8: seq=5 ttl=117 time=12.278 ms
64 bytes from 8.8.8.8: seq=6 ttl=117 time=12.161 ms
64 bytes from 8.8.8.8: seq=7 ttl=117 time=12.273 ms
64 bytes from 8.8.8.8: seq=8 ttl=117 time=12.164 ms
64 bytes from 8.8.8.8: seq=9 ttl=117 time=15.269 ms
^C
--- 8.8.8.8 ping statistics ---
10 packets transmitted, 10 packets received, 0% packet loss
round-trip min/avg/max = 12.132/12.557/15.269 ms

**Comment by fredamn76** [comment]
Pinging 8.8.8.8 works.

**Comment by jmbannon** [comment]
how about `ping youtube.com`, maybe it's DNS related

**Comment by fredamn76** [comment]
root@e4c0364ef13e:/# ping youtube.com
PING youtube.com (0.0.0.0): 56 data bytes
64 bytes from 127.0.0.1: seq=0 ttl=64 time=0.042 ms
64 bytes from 127.0.0.1: seq=1 ttl=64 time=0.049 ms
64 bytes from 127.0.0.1: seq=2 ttl=64 time=0.050 ms
64 bytes from 127.0.0.1: seq=3 ttl=64 time=0.051 ms
64 bytes from 127.0.0.1: seq=4 ttl=64 time=0.050 ms
64 bytes from 127.0.0.1: seq=5 ttl=64 time=0.049 ms
64 bytes from 127.0.0.1: seq=6 ttl=64 time=0.048 ms
64 bytes from 127.0.0.1: seq=7 ttl=64 time=0.064 ms
64 bytes from 127.0.0.1: seq=8 ttl=64 time=0.051 ms
64 bytes from 127.0.0.1: seq=9 ttl=64 time=0.058 ms
64 bytes from 127.0.0.1: seq=10 ttl=64 time=0.053 ms
64 bytes from 127.0.0.1: seq=11 ttl=64 time=0.051 ms
64 bytes from 127.0.0.1: seq=12 ttl=64 time=0.050 ms
64 bytes from 127.0.0.1: seq=13 ttl=64 time=0.053 ms
64 bytes from 127.0.0.1: seq=14 ttl=64 time=0.067 ms
64 bytes from 127.0.0.1: seq=15 ttl=64 time=0.052 ms
^C
--- youtube.com ping statistics ---
16 packets transmitted, 16 packets received, 0% packet loss
round-trip min/avg/max = 0.042/0.052/0.067 ms

**Comment by fredamn76** [comment]
Seems to be my Pi-hole that is blocking youtube.com. Whitelisting solved it.
