### ISSUE TITLE
Cron not loading?

### ISSUE THREAD

**Issue by cinderblockgames** [jmbannon/ytdl-sub#570]
I get this error when trying to enable cron:

```
Invalid tarball, could not download linuxserver/mods:universal-cron
```

Any direction would be helpful. :)

**Comment by jmbannon** [comment]
Your docker command/compose has `DOCKER_MODS=linuxserver/mods:universal-cron` right? It might be down temporarily, give it a few more tries today and if it's still down by tomorrow we can contact linuxserver

**Comment by cinderblockgames** [comment]
```
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/New_York
      - DOCKER_MODS=linuxserver/mods:universal-cron
```

I'll give it time.  Thanks!

**Comment by cinderblockgames** [comment]
I'm thinking this might be a connectivity problem.  Is there a way to get the mods in offline, or to redirect to a local docker registry?

**Comment by cinderblockgames** [comment]
Okay, this is working:

__**/etc/periodic/hourly**__
```
#!/bin/bash
echo 'Cron started, running ytdl-sub...' > /config/output.log
ytdl-sub --config=/config/config.yaml sub /config/subscriptions.yaml >> /config/output.log
```

__**/etc/cont-init.d/99-crond**__
```
#!/bin/bash
crond
```

**Comment by jmbannon** [comment]
If you update your container, these files will disappear unless you mount those directories. I would recommend trying to get the dockermod working.

Also for storing logs, protip :) https://ytdl-sub.readthedocs.io/en/latest/config.html#persist-logs
