### ISSUE TITLE
Metadata not redownloaded with change in recent video window.

### ISSUE THREAD

**Issue by sacherjj** [jmbannon/ytdl-sub#588]
When a sub with only_recent_videos setting is increased or converted to full, there is no new metadata downloaded, so it appears that no videos fit the criteria.  The only fix I've found is to remove the data file for that sub to force redownload to pull extra data.

If the recent window time was stored with the file, then a check, if increased past current data or converted to unrestricted, could trigger downloading missing metadata.

**Comment by jmbannon** [comment]
Try this https://github.com/jmbannon/ytdl-sub/wiki/FAQ#id5

**Comment by jmbannon** [comment]
Feel free to reopen if that doesn't fix the issue, i'm 99% sure it will :-)
