### ISSUE TITLE
Download Lives

### ISSUE THREAD

**Issue by cesarblancg** [jmbannon/ytdl-sub#595]
Hello, 
Are there any chance that a Youtube Live can be downloaded?
For example, with [this ](https://www.youtube.com/@jaidenanimations/streams)channel, she has 3 month old lives and ytdl-sub doesn't detect them.

I saw there is a match_filters option that can exclude lives, but when I try to add them to the config file, it doesn't find anything.

**Comment by cesarblancg** [comment]
I searched in your discord and found the answer:

config:
yt_channel_with_streams:
  preset:
    - "jellyfin_tv_show_collection"
    - "season_by_collection__episode_by_year_month_day"
    - "only_recent_videos"
    - "fixed_quality"
    - "sponsorblock"
    - "collection_season_1"
    - "collection_season_2"
  overrides:
    tv_show_genre: "YouTube"
    tv_show_directory: "/tv_shows/YouTube"
    collection_season_1_name: "Videos"
    collection_season_1_url: "{tv_show_channel_url}"
    collection_season_2_name: "Live Streams"
    collection_season_2_url: "{tv_show_channel_url}/streams"
  ytdl_options:
      cookiefile: "/config/cookie_file.txt"
      format: "bestvideo[height<=720]+bestaudio/best[height<=480]"
      postprocessor_args:
        - "-c:v"
        - "h264_nvenc"
      merge_output_format: "mp4"

subscription:
Channel1:
  preset:
    - "yt_channel_with_streams"
  overrides:
    tv_show_name: "Channel1"
    tv_show_channel_url: "https://www.youtube.com/@Channel1"

**Comment by cesarblancg** [comment]
I searched in your discord and found the answer:

config:
yt_channel_with_streams:
  preset:
    - "jellyfin_tv_show_collection"
    - "season_by_collection__episode_by_year_month_day"
    - "only_recent_videos"
    - "fixed_quality"
    - "sponsorblock"
    - "collection_season_1"
    - "collection_season_2"
  overrides:
    tv_show_genre: "YouTube"
    tv_show_directory: "/tv_shows/YouTube"
    collection_season_1_name: "Videos"
    collection_season_1_url: "{tv_show_channel_url}"
    collection_season_2_name: "Live Streams"
    collection_season_2_url: "{tv_show_channel_url}/streams"
  ytdl_options:
      cookiefile: "/config/cookie_file.txt"
      format: "bestvideo[height<=720]+bestaudio/best[height<=480]"
      postprocessor_args:
        - "-c:v"
        - "h264_nvenc"
      merge_output_format: "mp4"

subscription:
Channel1:
  preset:
    - "yt_channel_with_streams"
  overrides:
    tv_show_name: "Channel1"
    tv_show_channel_url: "https://www.youtube.com/@Channel1"

**Comment by jmbannon** [comment]
They used to download by default, but changed recently. Glad you figured it out!

**Comment by tylerdak** [comment]
```
cookiefile: "/config/cookie_file.txt"
format: "bestvideo[height<=720]+bestaudio/best[height<=480]"
postprocessor_args:
- "-c:v"
- "h264_nvenc"
merge_output_format: "mp4"
```

Is any of this actually necessary or just personal preference?

**Comment by jmbannon** [comment]
@tylerdak These are personal preference settings. The nvenc arg is indeed needed if using the gpu passthrough container
