### ISSUE TITLE
SpeedLimit

### ISSUE THREAD

**Issue by TheMrThx** [jmbannon/ytdl-sub#601]
Hi,

Is there any way to set speedlimit of downloading from youtube?

**Comment by jmbannon** [comment]
Yes, using `ytdl_options`:
https://ytdl-sub.readthedocs.io/en/latest/config.html#ytdl-options

There is a ratelimit arg here, which I think is in bytes:
https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/YoutubeDL.py#LL458C44-L458C44
