### ISSUE TITLE
ytdl_options passing values of type str when it should be int

### ISSUE THREAD

**Issue by JohnEridium** [jmbannon/ytdl-sub#602]
Hi,
I'm very new to ytdl-sub and just trying to figure out the config/sub files.

When trying to download the channel PinocchioP, I get the following error: "ERROR: '>' not supported between instances of 'str' and 'int'"
I could not find a similar error here, the only one slightly resembling mine had the solution listed to use python 3.10, which I already am.
I'll attach my config, sub list and the error log, if you need any more infos, please let me know (due to GitHub being picky about file names, my both yamls are in the "Archive.zip" file).

Environment infos:
- OS: Ubuntu 22.04.2 LTS - LXC container on Proxmox 7.4
- uname -a: `5.15.102-1-pve #1 SMP PVE 5.15.102-1 (2023-03-14T13:48Z) x86_64 x86_64 x86_64 GNU/Linux`
- python --version: `Python 3.10.6`

[2023-04-30-235904.pinocchiop.error.log](https://github.com/jmbannon/ytdl-sub/files/11362510/2023-04-30-235904.pinocchiop.error.log)
[Archive.zip](https://github.com/jmbannon/ytdl-sub/files/11362511/Archive.zip)

**Comment by jmbannon** [comment]
Ahh it's from `'sleep_interval_subtitles': '5'` on your config. ytdl-sub passes it as a string when it infact should be an int. I think ytdl-sub will need to hardcode a mapping of `ytdl_options` param names to types.

As a workaround, just disable it. Though you may be throttled from trying to scrape subs of every language

**Comment by jmbannon** [comment]
Oh I see you actually have quotes around it like a string in your config. Try removing those quotes and see if it works

**Comment by JohnEridium** [comment]
Thanks for the speedy reply!

I removed the quotes and it works now. I have some more problems with the thumbnails and channel banners not downloading but I'll create another issue for this.
