### ISSUE TITLE
Ignore filter 

### ISSUE THREAD

**Issue by jacroe** [jmbannon/ytdl-sub#604]
Is there a way to ignore certain files, either explicitly or via a regex pattern?

As an example, I would wish to download this [let's play playlist](https://www.youtube.com/playlist?list=PLRQGRBgN_Enq2DpbXjaL89BxSQGwLlr_0) except for the very last video in it. I can picture either using an `ignore_url` parameter list or some regex matching (`/marathon/i`).

Is any of that possible or already available?

**Comment by jmbannon** [comment]
Yes! See:

https://ytdl-sub.readthedocs.io/en/latest/config.html#match-filters
https://ytdl-sub.readthedocs.io/en/latest/config.html#regex

**Comment by jacroe** [comment]
@jmbannon I was only able to try it out today, but the `match_filters` worked like a charm. Thanks!
