### ISSUE TITLE
[FEATURE] Display download progress

### ISSUE THREAD

**Issue by ilkersigirci** [jmbannon/ytdl-sub#605]
Thank you for this awesome project. It is the only project that is perfectly working perfectly with jellyfin IMO. I am building a simple wrapper for this to enable myself trigger download from UI. It would be awesome if I can access download progress. That way, I can show to progress bar in the UI using websockets like in the [metube](https://github.com/alexta69/metube/blob/528bbd220a2530919b8dfdc4c19942b9aaa94f33/app/ytdl.py#LL87C1-L87C48).

**Comment by jmbannon** [comment]
Glad you like the project @ilkersigirci ! We're in the design phase of a UI/rest server for ytdl-sub, check out https://github.com/jmbannon/ytdl-sub/issues/600

Going to close this so we can consolidate front-end discussion in that issue

**Comment by foolab** [comment]
@ilkersigirci would you be kind enough to share your wrapper?
I am also considering doing the same.

**Comment by ilkersigirci** [comment]
Unfortunately I cannot. I abondened the project due to lack of resources and interest. Sorry.
