### ISSUE TITLE
downloading a playlist in reverse

### ISSUE THREAD

**Issue by JohnEridium** [jmbannon/ytdl-sub#606]
Hi, 

I have read this issue here: https://github.com/jmbannon/ytdl-sub/issues/389 because I want to download this playlist: https://www.youtube.com/playlist?list=PLPt9u4Iorcdjyl4fI0lgrfXe9-50r_tQM

even though I (mostly) followed the advice in the mentioned issue, the newest video in this playlist is still the first episode. What am I missing to make the oldest/first video in this playlist the first episode? So that future keynotes simply get attached as newer videos and get a higher episode count

attached is my preset and the relevant subscription block.
[demo-config.txt](https://github.com/jmbannon/ytdl-sub/files/11398216/demo-config.txt)
[demo-sub.txt](https://github.com/jmbannon/ytdl-sub/files/11398217/demo-sub.txt)

**Comment by jmbannon** [comment]
Remove download_reverse from the download section, and set `playlistreverse: True` in ytdl_options. I think you are reversing it twice which makes it not reversed lol

**Comment by jmbannon** [comment]
This is now solved automatically by https://github.com/jmbannon/ytdl-sub/commit/017db953bf6285ee2f669c5ac87ecabb0df0d20b
