### ISSUE TITLE
Release version container tags

### ISSUE THREAD

**Issue by npawelek** [jmbannon/ytdl-sub#627]
Currently there is a discrepancy where the images pushed to GHCR only contain the `latest` tag. Is it possible to tag pushes with the proper release versions?

**Comment by jmbannon** [comment]
It's possible but I didn't bother because ytdl-sub is intended to be a rolling release - always using the latest is recommended and will always be backwards compatible

**Comment by philipcristiano** [comment]
I'd also love release-tags applied to Docker images. Containers can run for a long time and triggering via CI with a new tag ensures that hosts get the correct version without needing to pull `latest` every time. With k8s/nomad, retriggering a download of a running app is a bit more strange than pushing a new config that includes the latest tag.

**Comment by npawelek** [comment]
I've sort of combated this by pinning updates with the image digest SHA, which allows things like Renovate to know when image updates exist and to apply them. It doesn't replace proper semantic tagging, but does provide some level of control.

**Comment by philipcristiano** [comment]
Yeah I'm using the SHA now and leaving comments about where/when the SHA was grabbed.

**Comment by jmbannon** [comment]
Version numbers should now be working on docker images :tada:
