### ISSUE TITLE
maintain_download_archive is not working

### ISSUE THREAD

**Issue by rafasamp** [jmbannon/ytdl-sub#628]
Setting the maintain_download_archive tag as boolean True in the configuration file is not possible. See error below:

`[ytdl-sub] Validation error in tv_show.overrides.maintain_download_archive: should be of type format string.`

See configuration file excerpt:

```
    overrides:
         maintain_download_archive: True
```

I have tried to set it as a string as follows:

```
    overrides:
         maintain_download_archive: "True"
```

**Comment by jmbannon** [comment]
it's a field in output_options, not overrides
https://ytdl-sub.readthedocs.io/en/latest/config.html#output-options
