### ISSUE TITLE
Rename Show/Subscription?

### ISSUE THREAD

**Issue by jacroe** [jmbannon/ytdl-sub#639]
Let's say I have a show named "Rick A" and have downloaded hundreds of videos with the size well in the 100s of gigabytes. I also have `.nfo` files, thumbnails, and subtitles all prefaced with the show's name. For example:

```
/path/to/tv_shows/Rick A
  /Season 2021
    Rick A - S2021E0317 - Pattys Day Video-thumb.jpg
    Rick A - S2021E0317 - Pattys Day Video.mp4
    Rick A - S2021E0317 - Pattys Day Video.nfo
    Rick A - S2021E0317 - Pattys Day Video.srt
  /Season 2022
    Rick A - S2022E1225 - Merry Christmas-thumb.jpg
    Rick A - S2022E1225 - Merry Christmas.mp4
    Rick A - S2022E1225 - Merry Christmas.nfo
    Rick A - S2022E1225 - Merry Christmas.srt
  poster.jpg
  fanart.jpg
  tvshow.nfo
```

Of course the `.nfo` files have the TV show name in them, too, as the `showtitle`. 

But now, because of a typo or not wanting to abbreviate or (in my specific case) wanting to make a more generic show name, I wanted to rename the show to "Rick Astley". Is there an easy or recommended way to go about this? Or am I stuck with either 1) writing a script to rename/edit everything or 2) changing the name in my `subscriptions.yaml` and re-downloading?

**Comment by jmbannon** [comment]
There is an experimental way to do it. On my phone and don't remember the arg exactly, but if you do ytdl-sub sub -h, you'll see something like --update-with-info-json.

There are a few caveats, but can be worked around.
1. It updates the entire subscription file - move the sub you want to change to a separate yaml file
2. You cannot change the subscription key, i.e. rick_a - this can stay the same
3. Changing the `tv_show_name` var will change the output folder - copy the entire TV show directory to this new folder name

Then update the yaml with your new tv_show_name, the do
 `ytdl-sub --dry-run sub --update-with-info-json temp_sub_file.yaml` to make sure it looks sane.

I'm aware this process is clunky, hoping to improve it at some point

**Comment by jmbannon** [comment]
This also requires each video to have an .info.json file, hopefully you have that

**Comment by jmbannon** [comment]
Closing as a dupe in favor of https://github.com/jmbannon/ytdl-sub/issues/536
