### ISSUE TITLE
Unable to download to nas

### ISSUE THREAD

**Issue by thisisawesome1994** [jmbannon/ytdl-sub#646]
Hi,

I want to download a subscription to a nas over samba, but when I do this from a windows 11 client, it doesnt recognize the samba server path correctly, which results in downloading the subscription to a cache folder, without recognizing or moving files to or for the right directory on the nas. Do you know how to fix this?

Awaiting your response,

Joannes Wyckmans

**Comment by jmbannon** [comment]
Can you post your config and subscription.yaml? You should be able to mount the samba in windows as a drive letter (i.e. D://), and have the output directory point to D://thisisawesome/path/to/tv_shows

**Comment by thisisawesome1994** [comment]
I tried to add the samba share directly as a //192.168.0.XX/ShareXX

For some reason that used to work I think, but now it doesn't .

Also, in Windows 11, I cannot find a way to mount a share as a drive letter anymore.
Maybe windows changed something I have to figure out.

I am aware that you used to be able to mount a network share as a drive letter.
I will try to see if I can find it.

**Comment by thisisawesome1994** [comment]
So I get this error after mounting network drive as letter

FileNotFoundError: [WinError 3] Het systeem kan het opgegeven pad niet vinden: 'Y:\\'

I only specified one \ after Y:/

Do you know why this happens?

Also, should I use powershell, or cmd?

Because there seem to be some inconsistencies between them when I use certain C applications. Some work at one of them, but not the other.

**Comment by jmbannon** [comment]
Please post your config and full error log. I think you also need Y:\\ because YAML escapes \

**Comment by jmbannon** [comment]
ytdl-sub should support `Y:/`, try forward slashes as well

**Comment by thisisawesome1994** [comment]
If I do the other way around, I get error for wrong yaml

**Comment by jmbannon** [comment]
Put strings around it

**Comment by jmbannon** [comment]
Going to close since I'm quite certain this is a user-error. Still happy to help in this thread though
