### ISSUE TITLE
adding flags to regex match causes the match to always fail

### ISSUE THREAD

**Issue by Behem07h** [jmbannon/ytdl-sub#650]
```'([/](?:releases|playlists)(?:[^/|\w]|$))/gi'```
The above regex should match the string `UCT6fzkIIQuAQIiJK3tt-keg/playlists`
 , but for some reason adding the /gi flag to the end causes it to fail. i've tried every combination of no quotes, single quotes, double quotes and both escaped and unescaped /gi, but in all combinations it seems to fail

in theory `(.*)/g` should also fail, but i've not tested it.

possibly the cause of https://github.com/jmbannon/ytdl-sub/issues/648, i cant remember if i had tested it with all the flags removed.

**Comment by jmbannon** [comment]
https://stackoverflow.com/posts/31916642/revisions

Python doesn't support regex modifiers at the end unfortunately

**Comment by jmbannon** [comment]
See https://stackoverflow.com/questions/500864/case-insensitive-regular-expression-without-re-compile
On adding markers w/out doing a regex compile (which is what ytdl-sub does)

**Comment by jmbannon** [comment]
https://stackoverflow.com/questions/28353897/how-to-use-inline-regex-modifier-in-python
