### ISSUE TITLE
aarch64 executable not working on Raspberry Pi 4

### ISSUE THREAD

**Issue by thisisawesome1994** [jmbannon/ytdl-sub#651]
Hi.
Just a question.

Is the aarch64 for arm64? I seem to get this error:

cannot execute binary file: Exec format error

Can you please elaborate?

Would like to make it work for raspberry pi 4.

Awaiting your response,

Joannes Wyckmans

**Comment by jmbannon** [comment]
Hi @thisisawesome1994 , RPI4 does support arm64 but many pi OS's are 32-bit, which ytdl-sub does not support via executable install.

If your OS is 32-bit, you can instead install python >=3.10 and do `pip install ytdl-sub`

**Comment by thisisawesome1994** [comment]
First of all, you closed my ticket without any questions.

Second of all, this are my errors in python and command lines using the raspberry pi 4

uname -a
Linux plex 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

for the python app

ytdl-sub sub subscriptions.yaml
Traceback (most recent call last):
  File "/usr/local/bin/ytdl-sub", line 5, in <module>
    from ytdl_sub.main import main
  File "/usr/local/lib/python3.9/dist-packages/ytdl_sub/main.py", line 3, in <module>
    from ytdl_sub.cli.main_args_parser import parser
  File "/usr/local/lib/python3.9/dist-packages/ytdl_sub/cli/main_args_parser.py", line 6, in <module>
    from ytdl_sub.utils.logger import LoggerLevels
  File "/usr/local/lib/python3.9/dist-packages/ytdl_sub/utils/logger.py", line 13, in <module>
    from ytdl_sub.utils.file_handler import FileHandler
  File "/usr/local/lib/python3.9/dist-packages/ytdl_sub/utils/file_handler.py", line 17, in <module>
    def get_file_extension(file_name: Path | str) -> str:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

the executable also dont work, while I have 64 bit arm64. 

cannot execute binary file: Exec format error

**Comment by jmbannon** [comment]
I closed it because I am certain it is a user error. I am still happy to help even if it's closed. 
Looks like you have an older python version. Can you do `python --version`

**Comment by jmbannon** [comment]
Looking closer though you are right that the executable should be working - my bad. If I'm being honest I am far from an expert on compilation/executable issues. Not really sure what's wrong tbh. For doing a pip install though, I do know 100% it's from an older python version

**Comment by jmbannon** [comment]
I see in your stack trace you're on Python 3.9, that is why

**Comment by thisisawesome1994** [comment]
python3 --version gives

Python 3.9.2

I will see if I can upgrade to a newer version, but the debian 64 bit arm version that is shipped with the raspberry pi 4 is kind of an alternative version to debian (raspbian). It should work with most debian applications, as it is somewhat compatible. I dont have ubuntu arm64 atm. That might solve the problem. I will keep you posted once I have a raspberry pi 4 that is running ubuntu arm64. Could also be due to the high version of the kernel. The kernel is quite new for modern standards. Even ubuntu is not having this new of a kernel until recently. I hope I can sort this out.

So in the mean time, what python version do you suggest? Should I add the armhf (32 bit arm) using add-architecture command in debian/ubuntu? would that solve the python launch issue?

**Comment by jmbannon** [comment]
python >=3.10 should work

**Comment by thisisawesome1994** [comment]
I did this to get python3.11 to work under raspberry pi 4 on raspbian 64 bit...

```
dpkg --add-architecture armhf
apt-get update
apt upgrade -y
apt-get install -y build-essential tk-dev libncurses5-dev libncursesw5-dev libreadline6-dev libdb5.3-dev libgdbm-dev libsqlite3-dev libssl-dev libbz2-dev libexpat1-dev liblzma-dev zlib1g-dev libffi-dev
wget https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tgz
tar zxf Python-3.11.4.tgz
cd Python-3.11.4
./configure --enable-optimizations
make -j 4
make altinstall
echo "alias python=/usr/local/bin/python3.11" >> ~/.bashrc
source ~/.bashrc
curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11
```

I used command:
pip3.11 install ytdl-sub 

to install the ytdl-sub package.

**Comment by thisisawesome1994** [comment]
Maybe add to your readme?

**Comment by jmbannon** [comment]
It already is :) https://ytdl-sub.readthedocs.io/en/latest/install.html#pip

**Comment by thisisawesome1994** [comment]
If you do only what is in the readme, you will get an error, because wrong python version. This full command will install correct python version on arm devices when not available in distro

**Comment by jmbannon** [comment]
Hello again! Regarding RPI4 aarch64 build, I stumbled upon this:
https://forum.r-selfhosted.com/t/psa-check-your-rpi-architecture/230

Might be that the OS kernel is 64bit, but user space is 32bit.
