### ISSUE TITLE
how to download subscriber only videos?

### ISSUE THREAD

**Issue by dreamonates** [jmbannon/ytdl-sub#680]
how can i set ytdl-sub to download special videos? 
some youtubers are providing seperate "unlisted" exclusive videos for their subscribers on the "community" tab of their channel, how i can get them downloaded one by one?

**Comment by jmbannon** [comment]
You'll probably need your cookie file, and then a URL that points to the community tab

**Comment by dreamonates** [comment]
i have the cookie.txt file present in the folder and set the path in the config file. how can i point the url ?

**Comment by jmbannon** [comment]
Use the community tab URL like any other URL in a ytdl-sub subscription

**Comment by dreamonates** [comment]
> Hmmm it should get all as url2, assuming you have the channel url as url1

i ddi that, i added the channel and community links as url1 and url2 but it didn't see the community section.
it started when i added them as url and url2, but then it only gets the first four videos from the community tab.

but putting it as a seperate subscription is doing the job just fine, so it's alright for me :)
