### ISSUE TITLE
Feature Request: Singular Download Option

### ISSUE THREAD

**Issue by ohare93** [jmbannon/ytdl-sub#683]
Love the setup of having things sorted into tv shows with the right metadata, plus the automation of keeping up to date with latest subscriptions. I could not go back to my old setup!

Yet, I also sometimes encounter an older video of someone I enjoy and want it in my system. Yet this video is older than the 2 month or 1 year timeline I have set for new video downloads. I simply wish to have a way, even just a command line option here to:
1. Download a specific video
2. If it matches any of the channels I already have setup then follow all the rules in the subscriptions.yaml
3. Except any download ranges, or anything that would cause the video not to download.

Would be great 👍 anyways, great effort here

**Comment by jmbannon** [comment]
This exists! See https://ytdl-sub.readthedocs.io/en/latest/usage.html#download-options

**Comment by jmbannon** [comment]
If you're downloading an older vid of a channel you already have, all you need to do is:

```ytdl-sub dl --preset <TV show preset without date-ranges> --overrides.url <URL to single vid> --overrides.tv_show_name "Same Name as your Subscription"
```

**Comment by jmbannon** [comment]
Then make it simpler using DL aliases

**Comment by ohare93** [comment]
Hmm, that documentation did not make this clear. The overrides url shown in the docs is to a channel, not a singular video.

I am glad it is possible to download a specific video while being in the system _but_ I don't want to have to convert my subscriptions.yaml to a command for each instance 😅 it's already a slight hassle to enter it into the command line, I don't want to have to decipher my own setup (that I did months ago) and then worry if I got it right 😅 

`ytdl-sub dl [url]` with it auto using the sub file as normal, and auto matching the video's channel to my channel in the sub file (if exists) 😄

**Comment by jmbannon** [comment]
I should have clarified: for the single video, you'll want to use the TV show preset and set the URL to the single video itself. That preserves all the 'tv show formatting' even though it's just a single vid and not a channel.

You will not have to convert your subscription.yaml.

ytdl-sub dl [video url] and it linking to a subscription is a bit too specific of an ask if I'm being honest :P 

What I'm trying to describe above is, you can achieve what you want today using the `dl` command + some good aliases that are easy to remember.

**Comment by jmbannon** [comment]
So breaking this down:
```
ytdl-sub dl --preset <TV show preset without date-ranges> --overrides.url <URL to single vid> --overrides.tv_show_name "Same Name as your Subscription"
```

`--preset tv_show` will set the one-time download's preset to `tv_show`. This is where you have your TV show preset _without_ date range added to it. Make an addition preset called `tv_show_with_date_range` or something and use that in your subscriptions

`--overrides.url <video url>` will set the url to the single video you want

`--overrides.tv_show_name <The Show name, same as subscription>` ensures the video gets the same TV show name as your subscription so it will save to the proper directory with consistent metadata for the tv show name

**Comment by jmbannon** [comment]
To simplify your command, use DL aliases, something like:

```
configuration:
  dl_aliases:
    single-episode: "--preset tv_show --overrides.tv_show_name"
    url: "--overrides.url"
```

Turns the above command to:
`ytdl-sub dl --single-episode "Dunkey" --url "https://video.url.com"`

**Comment by jmbannon** [comment]
So the only extra part from your feature request is having to set the TV show name to the same as the subscription, which isn't so bad :P

**Comment by ohare93** [comment]
Hmm that is more workable than I was understanding 😅 thanks, I'll give it a go
