### ISSUE TITLE
Support option "best" for audio_extract.codec, which tries to keep original encoding

### ISSUE THREAD

**Issue by ostgor** [jmbannon/ytdl-sub#687]
https://discord.com/channels/994270357957648404/1138719204686700604

Feature request to add support for "best" in plugin option audio_extract.codec, the default option for yt-dlp's --audio-format when using the --extract-audio flag, the yt-dlp flag that seems to be used under the hood. The behavior for the "best" option is that it tries keeps the original audio format, but by specifying a codec the audio format not supported by the format will be re-encoded and will result in audio quality loss.

Code reference:
https://github.com/yt-dlp/yt-dlp/blob/db7b054a6111ca387220d0eb87bf342f9c130eb8/yt_dlp/postprocessor/ffmpeg.py#L487C12-L487C12

**Comment by jmbannon** [comment]
@ostgor should work now!
