### ISSUE TITLE
file_convert plugin, set yt-dlp merge format

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#689]

**Comment by Behem07h** [comment]
when downloading audio and video separately (such as in bestvideo+bestaudio), ytdlp remuxes the audio and video file together into a webm file. The merged file format can be specified via --merge-output-format, which officially supports avi, flv, mkv, mov, mp4, webm (and is also capable of remuxing to other containers not in this list). It takes converison rules, "mp4/mkv" will attempt to remux to mp4, and fallback to mkv if the mp4 conversion fails.
Setting merge-output-format thus avoids us remuxing twice when using the file_convert plugin (once to combine the audio and video, done by ytdlp, and once by the file_convert plugin from ytdlsub) and outsources the file conversion job to ytdlp.

In cases where audio and video are not downloaded separately (such as "best" in bestvideo+bestaudio/best), ytdlp does not need to remux the audio and video and so (need testing) will not use the merge-output-format setting as no files are being merged. Instead, --remux-video needs to be used, which supports avi, flv, gif, mkv, mov, mp4, webm, aac, aiff, alac, flac, m4a, mka, mp3, ogg, opus, vorbis, wav. remux-video takes conversion rules, such as "aac>m4a/mov>mp4/mkv", which will remux aac to m4a, mov to mp4 and anything else to mkv. 

both merge-output-format and remux-video copy the audio and video to the new container, so there is no codec conversion done. they will fail if all the attempted remuxing containers (as specified in their conversion rules) do not accept the audio or video codecs being copied

**Comment by catduckgnaf** [comment]
did latest preset solve this?

**Comment by Behem07h** [comment]
This issue is to make file_convert plugin take advantage of ytdlp remux_video and merge_output_format where it can. latest preset does not solve this
