### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by krafs** [jmbannon/ytdl-sub#694]
Would it be possible to include release notes on the changes for a given release? Preferably on the GitHub release? I subscribe to new releases on this repository, but whenever I get a notification about an update I can never tell what's changed.

GitHub has some great built-in features for automatically generating release notes from the PRs, if writing them by hand is too much.

Or are there actually release notes and I'm just looking in the wrong place? I did notice some old release notes exist as Discussions.

**Comment by jmbannon** [comment]
I usually post them in Discord which I know is bad practice. I'll try better to make discussions and eventually better docs on the release itself. The commit titles are usually pretty descriptive and sort-of serve as changelogs

**Comment by krafs** [comment]
If you know the commit messages will be good enough to convey the changes, then just including them in the Release text would be great! But whether or not you'd want that done automatically depends on how consistently you write descriptive commit messages :)

I don't know how much free time I have coming up, but let me know if I can help with  modifying the GitHub Action.

**Comment by jmbannon** [comment]
Yeah I should add that, I try to make all commit titles descriptive. Ideally a link to the  readthedocs would be best but the link isn't available until post-commit/release, so it's a sort of chicken-and-egg problem

Contributions are always welcome!

**Comment by catduckgnaf** [comment]
@catduckgnaf  I think a great Idea, but I do think it should be. in the release section. Easy enough to get an feed to a discord or anywhere else.

https://github.com/jmbannon/ytdl-sub/releases If you look at that page,  Definitely can be better.
Easy to edit, but it looks like it needs to be done by you, (unless you want to authorize me)

**Comment by jmbannon** [comment]
Got commit messages showing now! https://github.com/jmbannon/ytdl-sub/releases/tag/2023.08.30.post1
