### ISSUE TITLE
Implement new versioning system

### ISSUE THREAD

**Issue by catduckgnaf** [jmbannon/ytdl-sub#696]
We should implement a  new version tag system. (Another new one)

Edge/Nightly tag are all the changes through the month.. Then first of every month those changes are merged into the main branch.

This goes along well with the rolling release format of YTDL-SUB. 

Also given the current documentation preference of monthly announcements of all the changes for the month, I believe this system should fit the current workflow, encourage development without worrying about breaking changes, and provide more clear versioning and the potential for easier tags with docker imaging.

**Comment by jmbannon** [comment]
It's better ( easier for me to do rolling release - it's automated, requires code to be well tested, and easier to roll out fixes for breaking changes like when yt-dlp broke and had an emergency update.

**Comment by catduckgnaf** [comment]
That would still work with my solution of "edge" and a monthly cycle. 
Maybe when there is a need, now they would be to similar. tanks for considering.
