### ISSUE TITLE
Why download metadata if you fail a title match?

### ISSUE THREAD

**Issue by EvanCarroll** [jmbannon/ytdl-sub#705]
I have a title match in my subscription so the video is downloaded when the title fails the match, but the metadata is. It doesn't make sense to me why the metadata would be downloaded when it fails to match. This channel has like 2,000 videos.

**Comment by jmbannon** [comment]
Metadata contains fields like title or description that will get matched/filtered after all metadata gets pulled. Consider using https://ytdl-sub.readthedocs.io/en/latest/presets.html#chunk-initial-download

**Comment by EvanCarroll** [comment]
I don't get this response. It tells me the title what seems like _before_ it pulls the metadata,

> [ytdl-sub:downloader] Downloading metadata for Who Funds And Controls The Online Right?

Why can't when the index in pulled apply the title match before the metadata is pulled? That sounds like an easy optimizations for big channels where you only one one thing.

**Comment by jmbannon** [comment]
Ah yeah you can do that with a match filter, see https://ytdl-sub.readthedocs.io/en/latest/config.html#match-filters

**Comment by jmbannon** [comment]
To be clear, this and the regex plugin are different. This will skip the metadata pull whereas regex is post metadata

**Comment by EvanCarroll** [comment]
Ah, that's what I'm looking for. Also as a side note when I put on this preset `chunk_initial_download`, it works and only downs 20 before that subscription completes, the regexes fail to match, and nothing is downloaded (this is all desired). **But, then on rerunning it attempts to download the same 20** which has the same outcome.
