### ISSUE TITLE
Rewriting genres and channel metadata.

### ISSUE THREAD

**Issue by EvanCarroll** [jmbannon/ytdl-sub#707]
It seems the method of writing genres is established with,

```yaml
overrides:
    tv_show_genre: "ytdl-sub"
```

I can change that to whatever I want, but it will only rewrite it when there is a new video. Is there a way to force a rewrite without say _manually_ deleting the channel video data?

**Comment by jmbannon** [comment]
There is an experimental `--update-with-info-json` arg that can update existing shows - that's the only way at this time

**Comment by jmbannon** [comment]
Closing in favor of https://github.com/jmbannon/ytdl-sub/issues/536
