### ISSUE TITLE
Feature request:  Integration with ntfy.sh

### ISSUE THREAD

**Issue by doc-jay** [jmbannon/ytdl-sub#709]
Great tool!  

Link to ntfy [github](https://github.com/binwiederhier/ntfy)

Would be a nice feature to integrate ntfy.sh so that it can easily grab the summary of what was downloaded after each cron job.

**Comment by Yankees4life** [comment]
It's probably a bit easier to get that with integration from this
https://github.com/caronc/apprise

Would love to see a feature like this for my personal discord server

**Comment by jmbannon** [comment]
Seems like you could do this pretty easily within the CLI: https://docs.ntfy.sh/examples/#examples

**Comment by doc-jay** [comment]
True, i just don't know how i could have it send the summary that is displayed at the end of a job that is ran.

**Comment by jmbannon** [comment]
Something like:
`output=$(ytdl-sub --log-level quiet --config /config/config.yaml sub subscriptions.yaml); curl -H prio:low -d "${output}" ntfy.sh/ytdl-sub`

Going to close in favor of doing that. If you get it working, please report back with your command :slightly_smiling_face:

**Comment by jmbannon** [comment]
Setting log-level to quiet will only output the summary log

**Comment by Yankees4life** [comment]
I found something even better for discord
https://github.com/projectdiscovery/notify

Something like
`ytdl-sub --log-level quiet --config /config/config.yaml sub subscriptions.yaml | notify`

**Comment by doc-jay** [comment]
![Screenshot_20230923-020310_ntfy.png](https://github.com/jmbannon/ytdl-sub/assets/11081155/2d6ed073-22c1-4280-a909-c53f5828f1a2)

Attaching a pic of the display of the output after it was sent to my ntfy instance.

I got it work by using your output variable.  It just isn't pretty.  I can go back to that project and hit them up with a question.  I'll post my final command if/when i get it somewhat readable.

Thanks for your idea!

**Comment by jmbannon** [comment]
The weird characters are color codes. Maybe they can add support to either strip them out or display properly. Worst case there is probably a way to do it in the command-line

**Comment by doc-jay** [comment]
Here is my final script.

```
#!/bin/bash
TOPIC_URL=http://myprivateIP:3030/YT
echo 'Cron started, running ytdl-sub...'
output=$(ytdl-sub --log-level quiet --config /config/config.yaml sub /config/subscriptions.yaml | sed 's/\x1B\[[0-9;]*[JKmsu]//g')
echo '$output'
curl -u :mysecretkey -H prio:low -d "${output}" ${TOPIC_URL}
```

Now I'd like to figure out how to tell it if there are any downloads then run the curl.  If the output is all zeros then don't run the curl.

**Comment by doc-jay** [comment]
here is a final script that I'm using - it will only out put the row(s) of channels with vids that downloaded and will grab the channel name in the front of the row and use it as a 'title' in the message to my ntfy.sh instance.

`#!/bin/bash

TOPIC_URL=http://MYPRIVATEIP:3030/YTDL-SUB
echo 'Cron started, running ytdl-sub...'
output=$(ytdl-sub --log-level quiet --config /config/config.yaml sub /config/subscriptions.yaml | sed 's/\x1B\[[0-9;]*[JKmsu]//g')

# Filter lines that do not contain '0 0 0'
filtered_output=$(echo "$output" | grep -v '0 0 0')

# Extract the first word from each line and store it in 'channel_name'
channel_names=()
while read -r line; do
  channel_name=$(echo "$line" | awk '{print $1}')
  channel_names+=("$channel_name")
done <<< "$filtered_output"

# Join the extracted channel names into a single variable (comma-separated)
channel_name=$(IFS=,; echo "${channel_names[*]}")

echo "Extracted Channel Names: $channel_name"

# Check if 'filtered_output' contains more than just "Download Summary" before running curl
if [ -n "$filtered_output" ] && [ "$(echo "$filtered_output" | wc -l)" -gt 1 ]; then
  curl \
    -u :MYSECRETKEY \
    -H prio:low \
    -H "Title: $channel_name" \
    -d "${filtered_output}" \
    ${TOPIC_URL}
else
  echo "filtered_output does not contain valid data or only contains 'Download Summary'. Skipping curl."
fi`
