### ISSUE TITLE
Playlist as season preset?

### ISSUE THREAD

**Issue by EvanCarroll** [jmbannon/ytdl-sub#711]
Some channels lean towards grouping content into playlists. It would be nice if there was a preset to set the playlist to the season.

One example of this is opensecuritytraining

https://www.youtube.com/@OpenSecurityTraining/playlists

**Comment by jmbannon** [comment]
https://github.com/jmbannon/ytdl-sub/issues/502 closing as dupe. But yes, would be a nice feature
