### ISSUE TITLE
[Bug] "The file 'config.yaml' does not exist." But the config file is pointed to

### ISSUE THREAD

**Issue by Yankees4life** [jmbannon/ytdl-sub#715]
I'm trying to grab this channel here and I get this weird error
```
ytdl-sub dl --config "C:\Users\Jean\Documents\Projects\ytdl-sub\tv_show_config.yaml" --preset "tv_show" --overrides.tv_show_name "Maven Huffman" --overrides.url "https://youtube.com/@MavenKHuffman"
[ytdl-sub] The file 'config.yaml' does not exist.
```

I'm confused

**Comment by jmbannon** [comment]
--config needs to go behind dl

I will make a fix for this

**Comment by jmbannon** [comment]
Also for TV shows, I highly recommend using a subscription over a one-time dl

**Comment by Yankees4life** [comment]
> Also for TV shows, I highly recommend using a subscription over a one-time dl

Yeah...I just wanted to grab this for one time and not download it all the time
