### ISSUE TITLE
Cron uncaught error occurred

### ISSUE THREAD

**Issue by danshaw** [jmbannon/ytdl-sub#724]
Hey there. I'm running the docker container on my Synology NAS and having issues getting cron to work. Everything else seems to be working fine. Below is what I am seeing in the logs:

[ytdl-sub] An uncaught error occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ytdl_sub/main.py", line 26, in main
    _main()
  File "/usr/lib/python3.11/site-packages/ytdl_sub/main.py", line 18, in _main
    ytdl_sub.cli.main.main()
  File "/usr/lib/python3.11/site-packages/ytdl_sub/cli/main.py", line 312, in main
    with working_directory_lock(config=config):
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/utils/file_lock.py", line 48, in working_directory_lock
    lock_file = open(lock_file_path, "w", encoding="utf-8")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  PermissionError: [Errno 13] Permission denied: '/tmp/_config_.ytdl-sub-downloads'
  [ytdl-sub] Version 2023.09.15+0b62cc1

Here is my compose file:

services:
  ytdl-sub:
    image: ghcr.io/jmbannon/ytdl-sub:latest
    container_name: ytdl-sub
    environment:
      - PUID=1024
      - PGID=101
      - TZ=America/New_York 
      - DOCKER_MODS=linuxserver/mods:universal-cron
    volumes:
      - /volume1/docker/ytdl-sub/config:/config
      - /volume2/data/media/youtube:/tv_shows 
    restart: unless-stopped

I've followed the instructions for setting the right permissions for the cron jobs, so I am not sure if the PermissionError is the problem or just a symptom of another issue. Thanks for the help!

**Comment by jmbannon** [comment]
Did you resolve the issue @danshaw ?

**Comment by danshaw** [comment]
I did @jmbannon. I just needed to make sure that the UID and GID for docker matched the file system.
