### ISSUE TITLE
Filter away live streams by default

### ISSUE THREAD

**Issue by EvanCarroll** [jmbannon/ytdl-sub#729]
This a follow up to https://github.com/yt-dlp/yt-dlp/issues/8166 which is an issue I encountered while using `ytdl-sub`. If a channel has a live stream going on ytdl does not skip it during execution. Instead. It's held up indefinintely until the stream finishes. This is a bug, imho. I can't sync https://rumble.com/PressTV when they're airing because we just get stuck capturing the stream to disk.

Solution is very simple, `--match-filter '!is_live'`

**Comment by jmbannon** [comment]
Add it to the match filter plugin within your config:
https://ytdl-sub.readthedocs.io/en/latest/config.html#match-filters

**Comment by EvanCarroll** [comment]
@jmbannon  I can do that, but when would you ever not want to have that filter?

**Comment by jmbannon** [comment]
> @jmbannon I can do that, but when would you ever not want to have that filter?

Probably never for 99% of ytdl-sub use-cases. To your point, I'll add this to the TV show presets

**Comment by jmbannon** [comment]
Had to revert: https://github.com/jmbannon/ytdl-sub/commit/723c40b59be3737a19a9346c7fdaac34264b4938
Need to think of a seamless way to do this w/out breaking existing filters

**Comment by EvanCarroll** [comment]
Only speaking for `!is_live` you said this would not be useful 99% of the time. I guessed 100% of the time. If the 1% doesn't exist, maybe we can just elevate this out of yaml entirely and hard code the condition to ytdlp. Everything must be `!is_live`. Is there ever a case in which a live broadcast _can_ be handled by ytdlp-sub? Since you don't know what channel will broadcast live, it seems more than just undesirable to have any broadcast kill a multichannel sync job.

**Comment by jmbannon** [comment]
Regardless I need to think of how to add the match filter in a non-intrusive way

**Comment by jmbannon** [comment]
Alright @EvanCarroll , your wish has been granted: filters out livestreams by default
