### ISSUE TITLE
[Feature Request] Start video grabbing process regardless of cron schedule on container start

### ISSUE THREAD

**Issue by gauravpandeydotdev** [jmbannon/ytdl-sub#730]
This is a quality-of-life improvement.

It would be great to ytdl-sub start grabbing videos on container/app start. This should happen only at the start and then revert back to it's regular cron schedule. This is consistent with how most apps behave.

**Comment by jmbannon** [comment]
Going to close in favor of https://github.com/jmbannon/ytdl-sub/issues/732, let's move all discussion there
