### ISSUE TITLE
Adding multiple channels at once

### ISSUE THREAD

**Issue by Yankees4life** [jmbannon/ytdl-sub#740]
I would like there to be a way to add multiple YouTube channels into the config easily. Having to copy/paste over and over and over and set up names for each channel is tedious and very time consuming. I got about 100 on hand that I haven't even added to my config. Cheers

**Comment by jmbannon** [comment]
Read this and the subsequent section: https://ytdl-sub.readthedocs.io/en/latest/config.html#file-preset

You should be able to get subs as a one-liner

**Comment by Yankees4life** [comment]
Sounds interesting. I might set up a separate sub file for that.

I do want to get some of my channels by date so I'm not too sure if I can do that all in one sub yml file

**Comment by jmbannon** [comment]
Going to close in favor of https://github.com/jmbannon/ytdl-sub/issues/743
