### ISSUE TITLE
Cannot run ytdl-sub in nixos

### ISSUE THREAD

**Issue by rm-dr** [jmbannon/ytdl-sub#753]
Nixos has odd binary paths, so ytdl-sub fails to find ffmpeg at `/usr/bin/ffmpeg` even if it is installed.

**Comment by jmbannon** [comment]
Hey @rm-dr , you can change this in the config https://ytdl-sub.readthedocs.io/en/latest/config.html#ytdl_sub.config.config_validator.ConfigOptions.ffmpeg_path
