### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by magnetus26** [jmbannon/ytdl-sub#757]
Im a green newbie and having issues downloading a video from youtube.
im using windows 10 and im getting the following errors

C:\plex files\ytdl>ytdl-sub dl --preset "video" --download.url "https://youtu.be/4fyg3oFZ0S0?si=HMjpZbl6yey1d3es"

[ytdl-sub] Working directory lock not supported in Windows. Ensure only one instance of ytdl-sub runs at once using working directory C:\\plex files\\ytdl
[ytdl-sub] Validation error in cli-dl-00abb2cf: preset 'video' does not exist in the provided config.
Available prebuilt presets: best_video_quality, chunk_initial_download, collection_season_1, collection_season_10, collection_season_11, collection_season_12, collection_season_13, collection_season_14, collection_season_15, collection_season_16, collection_season_17, collection_season_18, collection_season_19, collection_season_2, collection_season_20, collection_season_21, collection_season_22, collection_season_23, collection_season_24, collection_season_25, collection_season_26, collection_season_27, collection_season_28, collection_season_29, collection_season_3, collection_season_30, collection_season_31, collection_season_32, collection_season_33, collection_season_34, collection_season_35, collection_season_36, collection_season_37, collection_season_38, collection_season_39, collection_season_4, collection_season_40, collection_season_5, collection_season_6, collection_season_7, collection_season_8, collection_season_9, jellyfin_tv_show_by_date, jellyfin_tv_show_collection, kodi_music_video, kodi_tv_show_by_date, kodi_tv_show_collection, max_1080p, plex_tv_show_by_date, plex_tv_show_collection, season_by_collection__episode_by_playlist_index, season_by_collection__episode_by_playlist_index_reversed, season_by_collection__episode_by_year_month_day, season_by_collection__episode_by_year_month_day_reversed, season_by_year__episode_by_download_index, season_by_year__episode_by_month_day, season_by_year__episode_by_month_day_reversed, season_by_year_month__episode_by_day
Your presets: include_info_json, sponsorblock, tv_show

[config.txt](https://github.com/jmbannon/ytdl-sub/files/12875624/config.txt)
[subscriptions.txt](https://github.com/jmbannon/ytdl-sub/files/12875626/subscriptions.txt)

attached are my config and subscriptions files. I just renamed them to .txt so they can be uploaded but they have a .yaml extension.
any help will be greatly appreciated
best regards,
Miguel

**Comment by jmbannon** [comment]
Hi @magnetus26 , your config doesn't have a `video` preset. Assuming you're going through the walkthrough, there is a guide on building a config which includes the `video` preset

**Comment by magnetus26** [comment]
for the life of me I cant make this to work.
I went through the walkthrough and cant find anything on `video preset`
I try I dry run and having directories issues. Windows  wont recognize spaces. I try copying all the file to my C root and no joy.
all I need is to download a yt video file at the time, I dont need multiple urls ( will be nice ) or a play list.
can you provide me with an example of `video preset`

this is the errors that im getting when try to dry run:


```
C:\ytdl>ytdl-sub --dry-run --config C:\\ytdl\\config.yaml
[ytdl-sub] Working directory lock not supported in Windows. Ensure only one instance of ytdl-sub runs at once using working directory C:\\plex files\\ytdl
[ytdl-sub] Must provide one of the commands: sub, dl, view

C:\ytdl>

```

```
C:\plex files\ytdl>ytdl-sub --dry-run --config C:\\plex files\\ytdl/config.yaml
usage: ytdl-sub [-h] [-v] [-c CONFIGPATH] [-d] [-l quiet|info|verbose|debug] [-t TRANSACTIONPATH] [-st]
                {sub,dl,view} ...
ytdl-sub: error: argument subparser: invalid choice: 'files\\\\ytdl/config.yaml' (choose from 'sub', 'dl', 'view')

```

```
C:\plex files\ytdl>ytdl-sub --dry-run --config C:\\plex files\\ytdl\config.yaml
usage: ytdl-sub [-h] [-v] [-c CONFIGPATH] [-d] [-l quiet|info|verbose|debug] [-t TRANSACTIONPATH] [-st]
                {sub,dl,view} ...
ytdl-sub: error: argument subparser: invalid choice: 'files\\\\ytdl\\config.yaml' (choose from 'sub', 'dl', 'view')

```

thanks 
Miguel

**Comment by jmbannon** [comment]
https://github.com/jmbannon/ytdl-sub/wiki/3.-Creating-and-Using-Your-First-Config#creating-the-config

**Comment by magnetus26** [comment]
great got it to work, I downloaded my 1st video, now to add more stuff like syntax to plex and change extension to mkv

thanks
Miguel
