### ISSUE TITLE
`ytdl-sub-gui` docker image using LSIO's code-server image

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#760]
the end-product should practically be a copy-paste of these two files:

ubuntu dockerfile: https://github.com/jmbannon/ytdl-sub/blob/master/docker/Dockerfile.ubuntu
github package workflow: https://github.com/jmbannon/ytdl-sub/blob/master/.github/workflows/package-ubuntu.yaml

with the few changes being a new base image in the dockerfile pointing to LSIO's code-server image (w/a specific version), and updated names in the workflow to have the published image name be ytdl-sub-gui

**Comment by tyzbit** [comment]
I love this idea, but I do want to offer an alternative to consider. [Filebrowser]https://github.com/filebrowser/filebrowser) is an extremely lightweight (the Docker image is 14MB) Golang web-based file browser that as luck would have it, can edit files within the app and has basic syntax support for YAML syntax highlighting (but definitely not linting or typo detection). Plus its main functionality is a very reliable storage manager for file and folder operations, which is quite handy to me in managing folders of media as well as configs.

**Comment by jmbannon** [comment]
@tyzbit Thanks for your suggestion. I don't think it has a terminal though which IMO is vital, plus the VScode editor is way more powerful. I'm not worried about bloat/size since we have a slim, headless alpine linux alternative.

**Comment by tyzbit** [comment]
Makes sense, plus with extensions and shipping premade configs with it, Code can be powerful _and_ standardized to help troubleshooting and support. Thanks for considering it!

**Comment by jmbannon** [comment]
Added the code-server image! See https://ytdl-sub.readthedocs.io/en/latest/install.html#gui for install instructions
