### ISSUE TITLE
Select audio track

### ISSUE THREAD

**Issue by tcaenen** [jmbannon/ytdl-sub#768]
Hello,

Do you have any idea on how to select the language from the audio track ?

this video for example : https://www.youtube.com/watch?v=3wnrucQG_g4
It got downloaded with the english track whereas I wanted the french one.

The option in yt-dlp looks odd to add to the yt-dlp-options of ytdl-sub.

Would it be possible to download all the audio tracks in order to select the track as I do usually with my player ?

Thanks a lot for your work on this project !

**Comment by jmbannon** [comment]
Can you link a reference to how it's done in yt-dlp

**Comment by tcaenen** [comment]
I found this : https://www.reddit.com/r/youtubedl/comments/114624f/how_to_choose_audio_language_for_youtube_video/

That said : 

> If for automation, you want to add something like [language=en] to the ba parts of your -f

With the example : 

> Changed the conf file code to -f "bv*[ext=mp4]+ba[ext=m4a][language=en]/b[ext=mp4] / bv*+ba/b" and continued with the original code yt-dlp -S +size,+br,+res,+fps https://youtu.be/TJ2ifmkGGus and got what I wanted.

**Comment by jmbannon** [comment]
If that doesn't work, try setting format manually: https://ytdl-sub.readthedocs.io/en/latest/config.html#format

**Comment by tcaenen** [comment]
It worked ! 
With the ytdl_options -> extractor_args -> youtube -> lang
I must say I was skeptical as I already saw this parameter and though it applied only on metadata (title and description) but it looks be smarter than only this.
Thank you !
