### ISSUE TITLE
Missing tvshow.nfo

### ISSUE THREAD

**Issue by danmed** [jmbannon/ytdl-sub#805]
Just finished scraping a couple of channels and whilst 1 of them has a tvshow.nfo, the other does not.. meaning that Kodi can't scrape it..

Is there any way to force it to create the nfo file?

**Comment by jmbannon** [comment]
Can you provide your config/subscriptions file?

**Comment by jmbannon** [comment]
I think it's probably from the tvshow.nfo not writing until the subscription is complete. Should be the other way around, and made first

**Comment by jmbannon** [comment]
I added this https://github.com/jmbannon/ytdl-sub/pull/809 and verified it will create the tvshow.nfo after downloading the first entry. Going to close but happy to help if it's still an issue
