### ISSUE TITLE
ytdl option no_playlist doesnt work

### ISSUE THREAD

**Issue by RogueGhost93** [jmbannon/ytdl-sub#832]
one of the presets

  TV Show No PLaylist:
    preset:
      - "base"
    overrides:
      no_playlist: True
        
  i also tried 
  
    TV Show No PLaylist:
    preset:
      - "base"
    ytdl_options:
      no_playlist: True
    overrides:
      no_playlist: True
      
      
 now, the problem is that in the logs no_playlist argument is correctly passed but for some reason ytdl-sub still downloads the whole playlist which i really want to avoid, maybe there is a better way of downloading a single video and skipping the rest of the playlist? Thanks for any help
 
 part of the logs
 ytdl_options: {'ignoreerrors': True, 'outtmpl': 'ytdl-sub-working-directory/Michael Saylor/%(id)s.%(ext)s', 'writethumbnail': False, 'ffmpeg_location': '/usr/bin/ffmpeg', 'download_archive': 'ytdl-sub-working-directory/Michael Saylor/ytdl-sub-Michael Saylor-download-archive.json', 'match_filter': <function match_filter_func.<locals>._match_func at 0x7fb46e2eba60>, 'format': '(bv*[height<=1080]+bestaudio/best[height<=1080])', 'break_on_existing': True, 'merge_output_format': 'mp4', 'max_downloads': 2, 'extractor_args': {'youtube': {'lang': ['en']}}, 'no_playlist': True, 'skip_download': True, 'writeinfojson': True}

**Comment by jmbannon** [comment]
My guess is you aren't applying the preset to your subscription. If you just want a single video, couldn't you use that individual URL link instead? Or are you trying to do a different kind of filter

**Comment by RogueGhost93** [comment]
But it is applied. You can even see in the log there is the ytdl option no_playlist: True

I guess i can, i ended up finding a way to get the url of the individual video but initially whatever k would do it would always load the whole playilist so i went for ytdl no playlist option. 
Regardless, the option should be working but it is not. I know it used to work on my yt-dlp before i switched to ytdl-sub! Amazing software btw and thank you so much. Even my wife will be able to use it xD

**Comment by jmbannon** [comment]
This is what you want: https://github.com/yt-dlp/yt-dlp/blob/2022.04.08/yt_dlp/YoutubeDL.py#L312

The python API differs from the CLI args: it's `noplaylist`

**Comment by RogueGhost93** [comment]
Thank you very much!
