### ISSUE TITLE
Add URL override variables beyond 20 

### ISSUE THREAD

**Issue by RogueGhost93** [jmbannon/ytdl-sub#833]
For some reason if i add more than 20 subrscriptions to any of the default presets for TV shows only first 20 get downloaded. In log url value doesnt go beyond url20. I tried using overrides from url1 all the way to url80 and only first 20 get downloaded. What is the best way to circumvent this? Thanks

https://github.com/jmbannon/ytdl-sub/blob/master/src/ytdl_sub/prebuilt_presets/helpers/url.yaml

i believe this would have to be changed but im not sure how exactly

**Comment by jmbannon** [comment]
I need to add more urls, lol. You mean 20 urls to a single subscription, right?
You can add more manually by making a custom preset look identical to that helper one.

If you don't mind me asking, what is your use-case? Why not have separate subscriptions for each URL?

**Comment by RogueGhost93** [comment]
My reason is that the guy i want to archive: Michael Saylor appears on many different podcasts and shows and i want all of them to be under one tv show called "Michael Saylor", with each new appereance i have to add another url but it stoppls the download after 20.


So youre saying i duplicate it and add more urls for example like url: {url28}? 
Thanks.

**Comment by jmbannon** [comment]
Closed by https://github.com/jmbannon/ytdl-sub/pull/874
