### ISSUE TITLE
Add default "studio" or "network"

### ISSUE THREAD

**Issue by RogueGhost93** [jmbannon/ytdl-sub#834]
Add default studio or network to each tv show as "YOUTUBE", similar to genre.

**Comment by jmbannon** [comment]
Is this an info.json field? If so, this is now possible using functions:
`{ map_get(entry_metadata, 'studio', 'default value') }`

You can also hardcode your own value into the video tags

**Comment by RogueGhost93** [comment]
Im not sure but it looks lile jellyfin uses networks and kodi uses studios. Maybe it is in .nfo files. Im also not sure how to use those functions in ytdl-sub, are there docs on it?

**Comment by RogueGhost93** [comment]
![Screenshot_20231223-192707.png](https://github.com/jmbannon/ytdl-sub/assets/127423999/59db4cf2-0f20-40fd-8e99-e91a1ac9ab76)

This is SS from a movie .nfo file downloaded by radarr. It think both jellyfin and kodi read this properly. You can see the field studios

**Comment by RogueGhost93** [comment]
![Screenshot_20231223-193403.png](https://github.com/jmbannon/ytdl-sub/assets/127423999/f773c8ac-9cc6-47ea-a228-0dbf3237fa47)

This is from tv show Doctor Who downloaded by sonarr. It works well in jellyfin and kodi. Also, you can also make it default to Youtube so anyone has to change it only if they want skmething specific

**Comment by jmbannon** [comment]
You can find the source of the presets here: https://github.com/jmbannon/ytdl-sub/blob/master/src/ytdl_sub/prebuilt_presets/tv_show/episode.yaml

You can add to the NFO plugin options in your config to add this new field

**Comment by felichas** [comment]
Although @jmbannon 's  answer is obviously correct, and I understand it now, it wasn't obvious to me until I learned a lot more about the project.

This may save someone some time:
I added this to my `subscriptions.yaml`
at the same level that my `overrides:`, because I only get videos that I then "translate" to tv shows:

```yaml
  # Add <studio>Youtube</studio> to tvshow.nfo
  output_directory_nfo_tags:
    tags:
      studio: Youtube

  # Add <studio>Youtube</studio> to episode.nfo
  nfo_tags:
    tags:
      studio: Youtube
```
