### ISSUE TITLE
Override Titel in nfo

### ISSUE THREAD

**Issue by Serph91P** [jmbannon/ytdl-sub#835]
Sorry for my english :smile: 

Did not find anything for the titel that appears in the nfo or the media server, not the file name. Would be great to be able to edit those to something else.  Because the filename does not matter for me only for the media server. But the titel that is shown in the media server. The readability of this is kinda crazy 4999.2023-11-13 - Titel if you could change it to only be the Titel and the rest is not shown in the media server would be great. 

But maybe I did miss something and it can be changed?

**Comment by Serph91P** [comment]
> It is definitely possible to override the media server title. Which preset are you using

Thanks for the fast response.

Am using the example advanced configs.

**Comment by jmbannon** [comment]
Sorry meant player. If you are using Plex, you may need to set this: https://github.com/jmbannon/ytdl-sub/wiki/FAQ#plex-is-not-showing-my-tv-shows-correctly

**Comment by Serph91P** [comment]
> Sorry meant player. If you are using Plex, you may need to set this: https://github.com/jmbannon/ytdl-sub/wiki/FAQ#plex-is-not-showing-my-tv-shows-correctly

Using emby and set jellyfish as preset.

**Comment by jmbannon** [comment]
I actually haven't tested with Emby. It sounds like it's reading the filename and not the NFO. Try to change the scraper to explicitly read NFOs if you can

**Comment by Serph91P** [comment]
> I actually haven't tested with Emby. It sounds like it's reading the filename and not the NFO. Try to change the scraper to explicitly read NFOs if you can

already set to read the nfo, but in the nfo the titel is already like this. So it is reading it correclty I guess?
![grafik](https://github.com/jmbannon/ytdl-sub/assets/8904984/268c0ae4-a32e-4084-a809-606e094e3a9d)
![grafik](https://github.com/jmbannon/ytdl-sub/assets/8904984/fafb61d0-9341-4f53-a22e-8bbe3e4fcda7)

**Comment by Serph91P** [comment]
> I actually haven't tested with Emby. It sounds like it's reading the filename and not the NFO. Try to change the scraper to explicitly read NFOs if you can

Just checked again I dont know what is is reading but other files I have with nfo are working great this is from a ltt video:
![grafik](https://github.com/jmbannon/ytdl-sub/assets/8904984/a880e5ea-4693-4d4a-aa8c-dab97e6e4f06)
![grafik](https://github.com/jmbannon/ytdl-sub/assets/8904984/45f9d128-c8c4-415f-8cf5-c422d8124210)

And here another example of a twitch stream I use with nfo aswell.

![grafik](https://github.com/jmbannon/ytdl-sub/assets/8904984/0ef11fc4-c917-47a4-a218-69e8c3126699)
![grafik](https://github.com/jmbannon/ytdl-sub/assets/8904984/addd58b0-174d-45bd-9d80-68072dab57ae)

**Comment by jmbannon** [comment]
Oh I see, so you just want to drop the date. That can be done by overriding the `episode_title` variable: https://github.com/jmbannon/ytdl-sub/blob/master/src/ytdl_sub/prebuilt_presets/tv_show/episode.yaml#L40

**Comment by Serph91P** [comment]
> Oh I see, so you just want to drop the date. That can be done by overriding the `episode_title` variable: https://github.com/jmbannon/ytdl-sub/blob/master/src/ytdl_sub/prebuilt_presets/tv_show/episode.yaml#L40

Ah got it thanks.
