### ISSUE TITLE
--match-filter   Does not work

### ISSUE THREAD

**Issue by RogueGhost93** [jmbannon/ytdl-sub#836]
match_filters:
      filters:
        - "playlist_title != 'Nine Fraud'"
        
        also tried:
        - "playlisttitle != 'Nine Fraud'"
        - "playlisttitle != 'Nine Fraud'" 
        - "playlist_title!='Nine Fraud'" 
        - "playlist_title!=Favorites" --> to avoid using single quotes

I tried a few more options but none of them seem to work. They do work with using yt-dlp though.
I also tried them on individual playlists and on whole channels. 
Here are two different logs where i attempted the first line and then the second one listed above. Its clearly visible the filters are applied with preset but they are not applied when it comes to downloading.
![Screenshot_20231213_191412](https://github.com/jmbannon/ytdl-sub/assets/127423999/d117ebab-3197-48b9-a0b0-176eebb587dc)
![Screenshot_20231213_191349](https://github.com/jmbannon/ytdl-sub/assets/127423999/9b46bfa5-94df-4b41-bb93-c3b7bf9ba066)

here are the channel links if you wanna replicate:
    "Peter Schiff": "https://www.youtube.com/@peterschiff/playlists"
    #"Peter Schiff": "https://www.youtube.com/playlist?list=FLIjuLiLHdFxYtFmWlbTGQRQ"

**Comment by jmbannon** [comment]
When you tested, did you just do one at a time or did you have both Nine Fraud and Favorites filtered?

They need to be `&` on a single line, because separate match-filter lines acts as a conditional OR

**Comment by jmbannon** [comment]
Going to close because I'm not convinced match-filter is broken - it's pretty well tested. But happy to help discuss any further debugging

**Comment by RogueGhost93** [comment]
Sorry didnt have time earlier to answer and report what happend. You are right, it works as expected as long as they are on the single line. 

This is how i used it and it works.

        - "original_url!*=/shorts/ & playlist_title != 'Trending' & playlist_title != 'Liked videos' & playlist_title != 'Favorites' & playlist_title != 'Liked videos' & playlist_title != 'Shorts'"
