### ISSUE TITLE
ytdl-sub unable to write to output folder, video is being skipped on subsequent runs

### ISSUE THREAD

**Issue by pharmacologic** [jmbannon/ytdl-sub#842]
Hi, 

I experienced a power outage earlier, and while starting my servers back up, I had several docker containers start without having the network storage mounted.

I had already started ytdl-sub back up again, and it had no issues with the working folder (internal ssd), but when it got to moving the finished file to the output folder, it experienced a permissions issue (i.e. the docker container did not have the networked youtube folder mounted to write to)

```
[ytdl-sub] The following error occurred for the subscription FailRace: Survive the Hunt:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/subscriptions/subscription_download.py", line 375, in exception_handling
    yield
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/cli/entrypoint.py", line 113, in _download_subscriptions_from_yaml_files
    subscription.download(dry_run=dry_run)
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/subscriptions/subscription_download.py", line 362, in download
    return self._process_subscription(
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/subscriptions/subscription_download.py", line 320, in _process_subscription
    self._process_entry(
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/subscriptions/subscription_download.py", line 245, in _process_entry
    self._post_process_entry(
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/subscriptions/subscription_download.py", line 220, in _post_process_entry
    optional_plugin_entry_metadata = plugin.post_process_entry(entry)
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/plugins/nfo_tags.py", line 278, in post_process_entry
    self._create_nfo(entry=entry)
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/plugins/nfo_tags.py", line 181, in _create_nfo
    self.save_file(file_name=nfo_file_name, file_metadata=nfo_metadata, entry=entry)
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/ytdl_additions/enhanced_download_archive.py", line 737, in save_file
    self._enhanced_download_archive.save_file_to_output_directory(
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/ytdl_additions/enhanced_download_archive.py", line 660, in save_file_to_output_directory
    is_modified = self._file_handler.move_file_to_output_directory(
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/utils/file_handler.py", line 467, in move_file_to_output_directory
    os.makedirs(os.path.dirname(output_file_path), exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/channels/FailRace： Survive the Hunt'
[ytdl-sub] A permission error occurred:
[Errno 13] Permission denied: '/channels/FailRace： Survive the Hunt'
The user running ytdl-sub must have permission to this file/directory.
```

After restarting the container(s) with the network storage mounted, ytdl-sub appears to be skipping over the failed video (it was a single new video from a playlist), and moving to the next channel. 

I imagine the video must have been added to the download archive (and is therefore being excluded), despite not existing in the main youtube folder.

I'm using the `examples/advanced/tv_show_config.yml` with some minor tweaks to my preferences. I haven't explicitly set a download archive, I'm not sure where I would find it.

**Comment by jmbannon** [comment]
You can set the `ytdl_options.break_on_existing` to False to not break on existing videos, to grab the old ones.
If that does not work, you can explicitly remove entries in the archive file, which is found in the TV show's directory named 
 with the file named `.ytdl-sub-*`

**Comment by jmbannon** [comment]
The download archive also only saves after every entry file gets moved to the output directory, so I'm not sure how it could be skipped on a subsequent run

**Comment by pharmacologic** [comment]
> The download archive also only saves after every entry file gets moved to the output directory, so I'm not sure how it could be skipped on a subsequent run

Hm - I've checked the `.ytdl-sub-*` archive in the series/channel folder, and that video is not listed in there, as you suggest.

Could the sponsorblock delay be a factor? It was a video that had initially been skipped because it was <2 days old, and then it was only grabbing that one recent video from the channel when the output failed.

**Comment by jmbannon** [comment]
If a vid is <2 days old with the sponsorblock delay, then it will not get downloaded in that timeframe. I'm a bit confused though, were you expecting that video to be there even if it was <2 days old?

**Comment by pharmacologic** [comment]
> If a vid is <2 days old with the sponsorblock delay, then it will not get downloaded in that timeframe.

I do understand that

> I'm a bit confused though, were you expecting that video to be there even if it was <2 days old?

No, sorry, I was just wondering if it could be relevant to the behavior of the video being skipped (in some unexpected way). It was really just a shot in the dark. I just find it very curious, as I'd expect the software to retry the video even after failing.

It sounds like my immediate problem can be solved with the `ytdl_options.break_on_existing` setting. I'll try it out when I'm finished / at a good break point with this current run.

**Comment by jmbannon** [comment]
Can you provide your config and subscription file, that would help me debug much better

**Comment by pharmacologic** [comment]
Here's [a gist](https://gist.github.com/pharmacologic/11d7ea4434f0fcc577ea14f75eba53c6) with config and subscription files.

**Comment by jmbannon** [comment]
Is the bad behaving one a playlist by chance?

**Comment by pharmacologic** [comment]
Indeed it is. It was the very first one in my subscriptions list.

**Comment by jmbannon** [comment]
It could be that new vids get added to the end. ytdl-sub expects them to be added in the front. You have to explcitly set the param `ytdl_options.playlistreverse` to True

**Comment by pharmacologic** [comment]
The options `playlistreverse: True` and `break_on_existing: False` did not immediately work, it continued to be skipped by (apparently returning the first / oldest video from the playlist), but after several runs / a few days, the video in question did end up downloading again (successfully, this time). 

I'm still a little confused, but I figure for software that is geared toward automation, it's enough that the videos are downloaded *eventually.* I'll close this now.
