### ISSUE TITLE
Unable to add a period/full stop in channel names

### ISSUE THREAD

**Issue by tehseano** [jmbannon/ytdl-sub#844]
Trying to set the name of a channel to include a period in the name, and I can't seem to get it to work. I have tried all the following:

```
"Mr. Beast":  "https://www.youtube.com/@MrBeast/videos"
"Mr\u002E Beast":  "https://www.youtube.com/@MrBeast/videos"
'Mr. Beast':  "https://www.youtube.com/@MrBeast/videos"
'Mr\. Beast':  "https://www.youtube.com/@MrBeast/videos"
```

They all return as:

`[ytdl-sub] Beginning subscription dry run for  Beast`

And trying

`"Mr\. Beast":  "https://www.youtube.com/@MrBeast/videos"`

Just crashes the script.

**Comment by pharmacologic** [comment]
I've noticed this too. If the period is partway in the channel name (i.e. `J. Kenji López-Alt`), it will take everything following the period (` Kenji López-Alt`) as the channel name, using that for the output folder and download archive filename etc.

If the period is at the *end* of the channel name, (i.e. `let's talk about stuff.`), the channel name is taken as empty, and the files / season folders end up in the main output folder.

Renaming the folders / moving files, plus editing the `tvshow.nfo` has worked as a temporary fix.

**Comment by jmbannon** [comment]
Bugfix is almost ready to be pushed @pharmacologic @tehseano , but FYI it requires renaming download archive files if you have any with a period in the subscription name (see the PR's description)

**Comment by pharmacologic** [comment]
My two channel subscriptions containing periods are still behaving oddly with this bugfix (`ytdl-sub 2023.12.27+65bb5c0`).

Subscription `let's talk about stuff.` is output to folder `let's talk about stuff` with download archive `.ytdl-sub-let's talk about stuff-download-archive.json`

`J. Kenji López-Alt` ends up with output folder `J` and download archive `.ytdl-sub-J-download-archive.json`

The `tvshow.nfo` is affected too, receiving series titles `let's talk about stuff` and `J`.

**Comment by jmbannon** [comment]
@pharmacologic 

Can you run `ytdl-sub --version` ? Sounds like you may not be on latest

**Comment by jmbannon** [comment]
@pharmacologic You are right - still is a bug. Should _actually_ be fixed and properly tested in this: https://github.com/jmbannon/ytdl-sub/pull/861

**Comment by jmbannon** [comment]
Should be fixed and pushed @pharmacologic - let me know otherwise (again :wink:  )
