### ISSUE TITLE
Clean up source variable docs

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#85]
Source variables are information from the media downloaded from ytdlp that can be used to set file names or metadata. They are documented here:
https://ytdl-sub.readthedocs.io/en/latest/config.html#source-variables

If you notice, a few variables' formatting looks weird. Like this one:
https://ytdl-sub.readthedocs.io/en/latest/config.html#ytdl_sub.entries.variables.youtube_variables.YoutubeVideoVariables.artist

There are random asterisks, and it seems like the `NOTE` changes formatting in some way.

The documentation for these should get cleaned up. They are generated from the docstrings in here:
https://github.com/jmbannon/ytdl-sub/tree/master/src/ytdl_sub/entries/variables

The docs are created using reStructuredText (https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html) and the autodocs extension (https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html)

To build the docs locally, run `make docs`

**Comment by 9gl** [comment]
Hey @jmbannon  , I'm interested in contributing to this issue, so before I start working on it, would you mind sparing your time explaining what the issue is about and pointing me to some resources to get started .

**Comment by jmbannon** [comment]
Hi @9gl , thanks for your interest! I added a better description and some code links. Let me know if you have any questions :)
