### ISSUE TITLE
Remove Pillow dependency, use ffmpeg to convert image formats

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#86]
Here's where all the thumbnail/pillow logic exists:
https://github.com/jmbannon/ytdl-sub/blob/master/src/ytdl_sub/utils/thumbnail.py

There's a bug with yt-dlp that reports it downloading a jpg but actually downloads webp. Not sure if it's fixed yet.
For a first pass though I think we can just replace the PIL functions with an FFMPEG call using this helper class:
https://github.com/jmbannon/ytdl-sub/blob/master/src/ytdl_sub/utils/ffmpeg.py

All of the e2e test md5 hashes for jpgs will probably need to get updated when changing this:
https://github.com/jmbannon/ytdl-sub/blob/master/tests/e2e/youtube/test_channel_as_kodi_tv_show.py#L79

Make sure the image still looks good

**Comment by Maka0** [comment]
Pushed change in #84
