### ISSUE TITLE
keep_max_files of 0 only downloads 2 videos.

### ISSUE THREAD

**Issue by philipcristiano** [jmbannon/ytdl-sub#892]
The `keep_max_files` setting (as documented) should be ignored for <= 0 

https://github.com/jmbannon/ytdl-sub/blob/305d084a6d60064af147f299168938591a062ff8/src/ytdl_sub/config/preset_options.py#L265-L274

It seems like the `0` value gets passed through and (guessing) the property is truth-y when passed through 

https://github.com/jmbannon/ytdl-sub/blob/305d084a6d60064af147f299168938591a062ff8/src/ytdl_sub/subscriptions/subscription_ytdl_options.py#L97-L101 

In my configuration I'm defaulting to setting this to 0 but override it when I want a show limited to N videos. 

Tested on release [ytdl-sub 2024.01.10.post1](https://github.com/jmbannon/ytdl-sub/releases/tag/2024.01.10.post1) and not sure when this started happening.

**Comment by jmbannon** [comment]
Nice find and thanks for triaging! You are exactly right - I added the max_downloads optimization recently - need to see if it's 0 after applying the formatter.

Can make a fix later today, or review a PR if you're up for making one :wink:

**Comment by philipcristiano** [comment]
Don't think I'll have time to make a PR for it. Also no rush! Thanks for the awesome tool and quick response!
