### ISSUE TITLE
Patreon Embedded Videos No Longer Found

### ISSUE THREAD

**Issue by tehseano** [jmbannon/ytdl-sub#907]
I've trying to download some videos from Patreon using a cookie file and have been successful up until maybe a week ago (and am still a Patron and have updated the cookie just in case). Now when downloading patreon videos even when there is a confirmed video in the post, it yields:

```
[ytdl-sub:yt-dlp] [Patreon] 76443012: Downloading API JSON
[ytdl-sub:yt-dlp] ERROR: [Patreon] 76443012: No supported media found in this post
``` 

I found this issue with yt-dlp (https://github.com/yt-dlp/yt-dlp/issues/8973) as well recently, and someone had forked a fix that was temporary until the commit got pushed into the main yt-dlp branch.

Any idea on incorporating?

**Comment by jmbannon** [comment]
Closing since it's not a ytdl-sub issue, but still happy to help.

Once the fix is pushed to yt-dlp, you can install yt-dlp's latest version via pip. I think there are instructions on their readme somewhere

**Comment by tehseano** [comment]
> Closing since it's not a ytdl-sub issue, but still happy to help.
> 
> Once the fix is pushed to yt-dlp, you can install yt-dlp's latest version via pip. I think there are instructions on their readme somewhere

When the fix is done in yt-dlp, do those then get incorporated into ytdl-sub? Sorry I'm less familiar with how that works, I'd like to avoid using yt-dlp directly as I prefer ytdl-subs setup (and the issue happens using ytdl-sub).
