### ISSUE TITLE
Example to download Watch Later playlist

### ISSUE THREAD

**Issue by rjbutler** [jmbannon/ytdl-sub#911]
Can you provide an example that downloads the watch later playlist?  I used to have one that worked, but somewhere along the line of converting my configs to the new formats, it stopped working.  I've tried some very simple configs and it never downloads at all.

For example, should this work?  If not, can you provide the simplest example that should?  Thanks

Jellyfin TV Show by Date:
  "Watchlist Videos":
    overrides:
      url: "https://www.youtube.com/playlist?list=WL"
      tv_show_directory: "/media/playlist"  
      playlist_reversed: true     # I've also tried this false, and not provided at all.

I have something around 20 videos in the playlist and I always get:

No files changed for Watchlist Videos
[ytdl-sub] Download Summary:
Watchlist Videos     0 0 0     0 ✔
Total: 1             0 0 0     0 Success

**Comment by jmbannon** [comment]
I would try disabling break_on_existing, my guess is you downloaded one vid and it's starting at that point for the metadata search

**Comment by rjbutler** [comment]
I tried that and still no luck.  Thanks

**Comment by rjbutler** [comment]
I forgot to add cookies.txt, so it wasn't finding the playlist.
