### ISSUE TITLE
Sonarr List Sync from YT Channel or Playlist

### ISSUE THREAD

**Issue by ekk88d** [jmbannon/ytdl-sub#920]
It's been a long time coming for Sonarr, so it'd be great to integrate your project with that util. I'm sure that you're familiar with it.

Adding a Custom List in Sonarr is easy. It's not in the documentation, but I would think that your program provide the list to Sonarr. Maybe? I'm sure there is a connection to make, so let me know if you'd like a contact.

**Comment by jmbannon** [comment]
Sonarr-extended does this already I believe
