### ISSUE TITLE
Basic directory output for Kodi TV Shows... impossible?

### ISSUE THREAD

**Issue by ohhdemgirls** [jmbannon/ytdl-sub#921]
> https://github.com/jmbannon/ytdl-sub/blob/master/examples/tv_show_subscriptions.yaml#L2

I don't want this... ^^

How do I download a YouTube playlist (or channel) and have **all the videos in a single directory** with their **original YouTube titles** and NFOs written for Kodi as a TV show? Having spent hours over days in the documentation (which a lot of seems to 404) I don't seem to be able to do this if it's possible, help please.

Why? Because this...

> https://www.youtube.com/playlist?list=PL5iTj9psbPrNovFOg4pJJIyxiLAv2WAKB

doesn't require a season structure, I just want to add a playlist as a TV show, without season directories or weird episode titles like `s2021.e031701`

**Comment by jmbannon** [comment]
It is possible - see the following docs: https://ytdl-sub.readthedocs.io/en/latest/prebuilt_presets/tv_shows.html#example

You will want `season_by_collection__episode_by_playlist_index` for episode numbering

**Comment by jmbannon** [comment]
Going to close the issue but happy to continue answering questions
