### ISSUE TITLE
New web gui

### ISSUE THREAD

**Issue by Intrinsically-Sublime** [jmbannon/ytdl-sub#926]
So I really love this project but was overwhelmed by the learning curve in using it and found the vscode web ui even more daunting since I have never used it. Not wanting to learn how to use vscode I  thought I would have a go at making a web gui myself.

I am not a programmer so a thought I would bootstrap this by using tinyfilemanager as a  base. It is a single page php file server and I know a tiny little bit of html and php.

This is what I have come up with so far. [Tiny Subscription Manager](https://github.com/Intrinsically-Sublime/tiny-sub-webgui) 

The roadmap should explain where it is at right now. If anyone is interested in helping out that would be awesome. Did I mention I am not a programmer. What I have done has taken me a lot longer than someone experienced so if you know how to finish anything on the roadmap please help out.

It is mobile friendly and has light and dark themes. Let me know what you think of it, any suggestions you have and any help you can provide.
## Screenshots
Mobile | Desktop|
--- | ---
![](https://github.com/Intrinsically-Sublime/tiny-sub-webgui/blob/main/screenshots/add_sub_mobile.png?raw=true) | ![](https://github.com/Intrinsically-Sublime/tiny-sub-webgui/blob/main/screenshots/add_sub_desktop.png?raw=true)

**Comment by jmbannon** [comment]
This looks great! I will definitely play around with this at some point and get back to you w/suggestions + feedback.
For any ytdl-sub questions, feel free to pop in the discord and ask away

cc @LukeHagar
