### ISSUE TITLE
download-archive rebuild/check

### ISSUE THREAD

**Issue by MidnightAnnie** [jmbannon/ytdl-sub#937]
I have a few channels and playlists that I archive and due to an error on my side, there are a couple of videos missing from all subscriptions.

Is there any way to rebuild the download-archive or even a way for it to check what is missing?

I have tried checking the docs but I don't seem to find any options for it

it's much better then redownloading everything.

**Comment by jmbannon** [comment]
Set
```
ytdl_options:
  break_on_existing: False
```
on redownload, it should check every single video. Run with `--log-level debug` to see it in action
