### ISSUE TITLE
Working directory

### ISSUE THREAD

**Issue by nothing2obvi** [jmbannon/ytdl-sub#945]
How do I edit the working directory? My hard drive is getting filled up from all of the downloads. I have the path `/ytdl-sub/temp` mapped out to an external hard drive, but it doesn't seem to be downloading to this directory.

From `config.yaml`
```
configuration:
  working_directory: ‘/ytdl-sub/temp’
```

From `docker-compose.yml`
```
    volumes:
      - /Volumes/ExternalHardDrive/ytdl-sub:/ytdl-sub
```

**Comment by nothing2obvi** [comment]
I just changed the `config` folder to the external hard drive. That's fine for now.

**Comment by karlic** [comment]
It didn't seem to work for me either. It seems like the configuration entry was just ignored.

I solved it with the terminal command:
`ln -s /mnt/Emby/ytdl-sub-working-directory .ytdl-sub-working-directory`

**Comment by jmbannon** [comment]
config is only picked up automatically if you run ytdl-sub in the same dir as the config. Specify `--config /path/to/config.yaml` to be certain it gets picked up
