### ISSUE TITLE
[Feature Request] DeArrow Integration 

### ISSUE THREAD

**Issue by Yankees4life** [jmbannon/ytdl-sub#946]
I think it would be nice to have DeArrow implementation in this tool. This is just to curb the click bait environment YT has and I could easily use this tool to take out any videos I have no interest in watching (as I would know what's its about)

https://github.com/QuantumWarpCode/yt-dlp-dearrow

Cheers

**Comment by jmbannon** [comment]
I think you could install and use this today so long as you're on Linux. It's possible in ytdl-sub to call any pre/post yt-dlp processor

**Comment by Yankees4life** [comment]
> I think you could install and use this today so long as you're on Linux. It's possible in ytdl-sub to call any pre/post yt-dlp processor

Really? How? What would it look like on the config.yaml?

**Comment by jmbannon** [comment]
See https://github.com/jmbannon/ytdl-sub/issues/98#issuecomment-1182910402 @Yankees4life 
Might require digging in the DeArrow code a bit

**Comment by Yankees4life** [comment]
> See [#98 (comment)](https://github.com/jmbannon/ytdl-sub/issues/98#issuecomment-1182910402) @Yankees4life Might require digging in the DeArrow code a bit

Hmm...that seems doable. I'll give that a try

**Comment by jmbannon** [comment]
Going to close out since I probably won't do an official integration (maybe if it gets popular like sponsorblock), but still happy to help
