### ISSUE TITLE
CMD Error "oserror [Winerror 123]

### ISSUE THREAD

**Issue by rubin9family** [jmbannon/ytdl-sub#949]
when using "ytdl-sub sub" on cmd, it gives a weird os error. 
![Screenshot ytdl error](https://github.com/jmbannon/ytdl-sub/assets/102113251/93728221-4ac1-4051-82c6-fb97af48cd90)

How to Fix?

**Comment by jmbannon** [comment]
Can you post your config/subscription file. My guess is the OS does not like `?` in the file name. That should be solved in the prebuilt presets, which makes me think you're using a custom config?

**Comment by rubin9family** [comment]
Sorry for the delay. I fixed it by adding Sanitized {title_ sanitized} to the file name in config. windows 10 cannot handle certain characters and causes cmd errors. 

They should put in the Guid windows machines need _sanitized or crashes will come when video's name uses invalid characters.
