### ISSUE TITLE
An uncaught error occurred: Version 2024.04.03+ad72e1a

### ISSUE THREAD

**Issue by SterlynKong** [jmbannon/ytdl-sub#958]
[2024-04-05-033246.mattvidpro_ai.error.log](https://github.com/jmbannon/ytdl-sub/files/14886087/2024-04-05-033246.mattvidpro_ai.error.log)

**Comment by jmbannon** [comment]
```
[ytdl-sub:yt-dlp] ERROR: [youtube] X5uleMLZpjs: Video unavailable. This video is restricted. Please check the Google Workspace administrator and/or the network administrator restrictions.
```
Typically this gets skipped during the metadata scrape via `ignoreerrors: True` by default. There's a slim chance it went private during your scrape. Maybe try redownloading again
