### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by Noodlez1232** [jmbannon/ytdl-sub#961]
Making the dependencies hard on one version makes it much more difficult to package especially on distros like NixOS where in order to package it, the dependencies each need to be packaged as well in the case of this project. Perhaps it might be a good idea to instead of depending on specific versions, depend on their major (or major+minor) version numbers?

I also think moving to a `pyproject.toml` file wouldn't be a bad idea either, since this will allow the removal of the setup.cfg file.

Of course, I'm not just saying this and putting the burden on you, I'm willing to do this work. I am more gauging the interest in this.

I've already tested at least updating the PyYAML dependency and removing the `argparse` dependency (since it comes in the python stdlib), and it worked flawlessly. All drop-in.

**Comment by jmbannon** [comment]
This all sounds great! I've been meaning to move to a .toml but just haven't got around to it yet.

As for the deps, I'd be okay with setting it to the current major version so long as it's capped at that (minor versions should be okay to auto-upgrade).

A pull request would be greatly appreciated 😊
