### ISSUE TITLE
Download videos completely one by one

### ISSUE THREAD

**Issue by ajgon** [jmbannon/ytdl-sub#99]
This issue may be me misunderstanding some concepts, so sorry in advance! 

If I understand the flow, `ytdl-sub` firstly downloads all the given videos to temporary directory, and after that, starts organizing them in proper season/episode folders. This is a problem for bigger channels.

For example, I left ytdl-sub to download a relatively small channel (250 videos / 150GB). When I came back, I found out that container crashed after downloading all the videos, during processing phase (not ytdl-sub fault, I've set too strict limits and docker killed the container). This left me with a 150GB of temporary files. When I reran `ytdl-sub` it happily wiped out all the temporary files and started from scratch :D 

I'm not sure how big change it will be (especially, since I'm not Python dev), but wouldn't be better, to process every video completely - one by one? I.e. download temp files, merge them, preprocess, copy to destination directory and mark them as downloaded in `.ytdl-sub-loading_archive-download-archive.json`. Thanks to that, if something crashes, in worst case scenario `ytdl-sub` will start when it left off (assuming `break_on_existing: False`), instead of redownloading everything again and again.

Hope that makes sense :)

**Comment by jmbannon** [comment]
@ajgon Added in this PR https://github.com/jmbannon/ytdl-sub/pull/101
